ServerEvents.recipes(event => {
event.recipes.gtceu.assembler("gadget_destruction")
.itemInputs("minecraft:diamond_pickaxe")
.itemInputs("gtceu:lv_emitter")
.itemInputs("8x gtceu:steel_plate")
.itemInputs("64x gtceu:fine_copper_wire")
.itemInputs('#gtceu:batteries/lv')
.itemOutputs("buildinggadgets2:gadget_destruction")
.duration(400)
.EUt(30)

event.recipes.gtceu.assembler("gadget_building")
.itemInputs("gtceu:lv_emitter")
.itemInputs("gtceu:lv_sensor")
.itemInputs("8x gtceu:steel_plate")
.itemInputs("64x gtceu:fine_copper_wire")
.itemInputs('#gtceu:batteries/lv')
.itemOutputs("buildinggadgets2:gadget_building")
.duration(400)
.EUt(30)

event.recipes.gtceu.assembler("gadget_exchanging")
.itemInputs("gtceu:item_filter")
.itemInputs("gtceu:lv_sensor")
.itemInputs("8x gtceu:steel_plate")
.itemInputs("64x gtceu:fine_copper_wire")
.itemInputs('#gtceu:batteries/lv')
.itemOutputs("buildinggadgets2:gadget_exchanging")
.duration(400)
.EUt(30)

event.recipes.gtceu.assembler("gadget_copy_paste")
.itemInputs("buildinggadgets2:gadget_building")
.itemInputs("gtceu:mv_emitter")
.itemInputs("gtceu:mv_sensor")
.itemInputs("2x #gtceu:circuits/mv")
.itemInputs("4x gtceu:polyethylene_plate")
.itemInputs("8x gtceu:aluminium_screw")
.itemOutputs("buildinggadgets2:gadget_copy_paste")
.duration(400)
.EUt(120)


event.recipes.gtceu.assembler("gadget_cut_paste")
.itemInputs("minecraft:diamond_pickaxe")
.itemInputs("buildinggadgets2:gadget_building")
.itemInputs("gtceu:mv_emitter")
.itemInputs("gtceu:mv_sensor")
.itemInputs("2x #gtceu:circuits/mv")
.itemInputs("4x gtceu:polyethylene_plate")
.itemInputs("8x gtceu:aluminium_screw")
.itemOutputs("buildinggadgets2:gadget_cut_paste")
.duration(400)
.EUt(120)

event.remove({mod:"buildinggadgets2"})


})