ServerEvents.recipes(event => {
event.remove({mod:"enderio"})
//StaffOfTraveling
event.recipes.gtceu.assembler("staff_of_travelling")
.itemInputs("ae2:charged_staff")
.itemInputs("enderio:ender_crystal")
.itemInputs("32x gtceu:fine_platinum_wire")
.itemInputs('2x #gtceu:circuits/ev')
.itemOutputs("enderio:staff_of_travelling")
.duration(200)
.EUt(500)

//VibrantCrystal
event.recipes.gtceu.assembler("pulsaiting_crystal")
.itemInputs("gtceu:energy_crystal")
.itemInputs("enderio:vibrant_alloy_ingot")
.itemInputs("#gtceu:circuits/ev")
.itemOutputs('enderio:pulsating_crystal')
.duration(400)
.EUt(500)

//EnderCrystal
event.recipes.gtceu.assembler("ender_crystal")
.itemInputs("enderio:pulsating_crystal")
.itemInputs("2x gtceu:pulasaiting_alloy_frame")
.itemInputs('#gtceu:circuits/iv')
.itemInputs("gtceu:hv_sensor")
.itemOutputs("enderio:ender_crystal")
.duration(400)
.EUt(500)

//itemConduit
event.recipes.gtceu.assembler("item_conduit")
.itemInputs("4x gtceu:pulasaiting_alloy_nugget")
.itemInputs("8x enderio:conduit_binder")
.itemInputs("2x gtceu:brass_small_item_pipe")
.itemOutputs("8x enderio:item_conduit")
.inputFluids("gtceu:polyethylene 144")
.duration(200)
.EUt(120)

//FluidConduite
event.recipes.gtceu.assembler("ender_fluid_conduit")
.itemInputs("4x gtceu:pulasaiting_alloy_nugget")
.itemInputs("8x enderio:conduit_binder")
.itemInputs("2x gtceu:bronze_small_fluid_pipe")
.itemOutputs("8x enderio:ender_fluid_conduit")
.inputFluids("gtceu:polyethylene 144")
.duration(200)
.EUt(120)

//EnergeticAlloyDust
event.recipes.gtceu.mixer("energetic_alloy_dust")
.itemInputs('#forge:dusts/gold')
.itemInputs("minecraft:redstone")
.itemInputs("minecraft:glowstone_dust")
.itemOutputs("3x gtceu:energetic_alloy_dust")
.circuit(10)
.duration(100)
.EUt(30)

//VibrantAlloyDust
event.recipes.gtceu.mixer("vibrant_alloy_dust")
.itemInputs("3x gtceu:energetic_alloy_dust")
.itemInputs('#forge:dusts/ender_pearl')
.itemOutputs("4x gtceu:vibrant_alloy_dust")
.circuit(10)
.duration(100)
.EUt(120)

//CopperAlloyDust
event.recipes.gtceu.mixer("copper_alloy_dust")
.itemInputs('#forge:dusts/copper')
.itemInputs("gtceu:nether_quartz_dust")
.itemOutputs("2x gtceu:copper_alloy_dust")
.circuit(10)
.duration(100)
.EUt(30)

//ConductivAlloyDust
event.recipes.gtceu.mixer("conductive_alloy_dust")
.itemInputs('#forge:dusts/iron')
.itemInputs("minecraft:redstone")
.itemOutputs("2x gtceu:conductive_alloy_dust")
.circuit(10)
.duration(100)
.EUt(30)

//PulsaitingAlloyDust
event.recipes.gtceu.mixer("pulasaiting_alloy_dust")
.itemInputs("8x gtceu:vibrant_alloy_dust")
.itemInputs("2x gtceu:silicon_dust")
.itemInputs("#forge:dusts/copper")
.itemInputs("#forge:dusts/silver")
.itemOutputs("gtceu:pulasaiting_alloy_dust")
.circuit(10)
.duration(100)
.EUt(500)

//GenericItemPipe
event.recipes.gtceu.assembler("item_pipe")
.itemInputs("4x gtceu:aluminium_nugget")
.itemInputs("2x gtceu:cobalt_brass_small_item_pipe")
.itemInputs("2x gtceu:polyethylene_small_fluid_pipe")
.itemInputs("4x enderio:conduit_binder")
.itemOutputs("8x pipez:item_pipe")
.inputFluids("gtceu:polyethylene 144")
.circuit(10)
.duration(100)
.EUt(120)

//GenericFluidPipes
event.recipes.gtceu.assembler("fluid_pipe")
.itemInputs("4x gtceu:aluminium_nugget")
.itemInputs("2x gtceu:aluminium_small_fluid_pipe")
.itemInputs("2x gtceu:polyethylene_small_fluid_pipe")
.itemInputs("4x enderio:conduit_binder")
.itemOutputs("8x pipez:fluid_pipe")
.inputFluids("gtceu:polyethylene 144")
.circuit(10)
.duration(100)
.EUt(120)

//UpgradePipes
event.recipes.gtceu.assembler("basic_upgrade")
.itemInputs('#forge:plates')
.itemInputs('#gtceu:circuits/ulv')
.itemInputs("gtceu:lv_conveyor_module")
.itemOutputs("4x pipez:basic_upgrade")
.circuit(10)
.duration(50)
.EUt(30)
event.recipes.gtceu.assembler("improved_upgrade")
.itemInputs("gtceu:double_steel_plate")
.itemInputs('#gtceu:circuits/lv')
.itemInputs("gtceu:mv_conveyor_module")
.itemOutputs("4x pipez:improved_upgrade")
.circuit(10)
.duration(50)
.EUt(30)
event.recipes.gtceu.assembler("advanced_upgrade")
.itemInputs("2x gtceu:double_aluminium_plate")
.itemInputs('#gtceu:circuits/mv')
.itemInputs("gtceu:hv_conveyor_module")
.itemOutputs("4x pipez:advanced_upgrade")
.inputFluids("gtceu:polyethylene 144")
.circuit(10)
.duration(100)
.EUt(120)
event.recipes.gtceu.assembler("ultimate_upgrade")
.itemInputs("4x gtceu:double_stainless_steel_plate")
.itemInputs('#gtceu:circuits/hv')
.itemInputs("gtceu:hv_conveyor_module")
.itemOutputs("pipez:ultimate_upgrade")
.inputFluids("gtceu:polyethylene 288")
.circuit(10)
.duration(200)
.EUt(500)

//EnderIoFilter
event.recipes.gtceu.assembler("basic_item_filter")
.itemInputs("gtceu:item_filter")
.itemInputs("gtceu:conductive_alloy_plate")
.itemInputs('2x #gtceu:circuits/ulv')
.itemOutputs("2x enderio:basic_item_filter")
.circuit(10)
.duration(200)
.EUt(120)
event.recipes.gtceu.assembler("fluid_item_filter")
.itemInputs("gtceu:fluid_filter")
.itemInputs("gtceu:conductive_alloy_plate")
.itemInputs('2x #gtceu:circuits/ulv')
.itemOutputs('2x enderio:basic_fluid_filter')
.circuit(10)
.duration(200)
.EUt(120)
event.recipes.gtceu.assembler("advanced_item_filter")
.itemInputs("enderio:zombie_electrode")
.itemInputs('#gtceu:circuits/lv')
.itemInputs("2x enderio:basic_item_filter")
.itemInputs("8x gtceu:fine_red_alloy_wire")
.itemOutputs("2x enderio:advanced_item_filter")
.circuit(10)
.duration(200)
.EUt(500)

//ZombieElectrode
event.recipes.gtceu.assembler("zombie_electrode")
.itemInputs("eidolon:zombie_heart")
.itemInputs("4x gtceu:diode")
.itemInputs("2x gtceu:capacitor")
.itemInputs('#gtceu:circuits/mv')
.itemOutputs("enderio:zombie_electrode")
.circuit(10)
.duration(400)
.EUt(30)

//ReinforcedObsidian
event.recipes.gtceu.assembler("reinforced_obsidian_block")
.itemInputs("minecraft:obsidian")
.itemInputs("gtceu:steel_frame")
.itemInputs("4x gtceu:steel_rod")
.itemOutputs("2x enderio:reinforced_obsidian_block")
.circuit(10)
.duration(800)
.EUt(120)
})
