ServerEvents.recipes(event => {

//MEController
event.recipes.gtceu.allienassembler("controller")
.itemInputs("gtceu:desh_frame")
.itemInputs("kubejs:energy_manager1")
.itemInputs("6x gtceu:fluixsteel_plate")
.itemInputs("2x gtceu:certus_quartz_frame")
.itemInputs("16x gtceu:certus_quartz_bolt")
.itemInputs("32x gtceu:fine_red_alloy_wire")
.itemOutputs("ae2:controller")
.EUt(500)
.duration(400)

//Drive
event.recipes.gtceu.allienassembler("drive")
.itemInputs("12x gtceu:steel_plate")
.itemInputs("2x gtceu:steel_frame")
.itemInputs("2x ae2:logic_processor")
.itemInputs("4x ae2:fluix_glass_cable")
.itemOutputs("ae2:drive")
.inputFluids("gtceu:soldering_alloy 144")
.EUt(500)
.duration(400)

//chest
event.recipes.gtceu.allienassembler("chest")
.itemInputs("6x gtceu:steel_plate")
.itemInputs("gtceu:steel_frame")
.itemInputs("ae2:logic_processor")
.itemInputs("ae2:fluix_glass_cable")
.itemInputs("minecraft:chest")
.itemOutputs("ae2:chest")
.inputFluids("gtceu:soldering_alloy 144")
.EUt(500)
.duration(400)

//CellWorkbench
event.recipes.gtceu.assembler("cell_workbench")
.itemInputs("ae2:io_port")
.itemInputs("ae2:item_cell_housing")
.itemInputs("2x gtceu:good_electronic_circuit")
.itemInputs("32x gtceu:fine_red_alloy_wire")
.itemOutputs("ae2:cell_workbench")
.EUt(30)
.duration(200)

//EnergyAcceptor
event.recipes.gtceu.assembler("energy_acceptor")
.itemInputs("gtceu:hv_machine_hull")
.itemInputs("4x gtceu:mv_voltage_coil")
.itemInputs("32x gtceu:fine_black_steel_wire")
.itemInputs("4x gtceu:certus_quartz_frame")
.itemOutputs("ae2:energy_acceptor")
.inputFluids("gtceu:polyethylene 288")
.EUt(30)
.duration(200)

//EnergyCell
event.recipes.gtceu.allienassembler("energy_cell")
.itemInputs("4x gtceu:energy_crystal")
.itemInputs("2x gtceu:certus_quartz_frame")
.itemInputs("2x gtceu:basic_electronic_circuit")
.itemInputs("8x gtceu:certus_quartz_plate")
.itemOutputs("ae2:energy_cell")
.inputFluids("gtceu:non_conducting_glue 288")
.EUt(500)
.duration(400)
event.recipes.gtceu.allienassembler("dense_energy_cell")
.itemInputs("4x ae2:energy_cell")
.itemInputs("4x gtceu:desh_frame")
.itemInputs("2x #gtceu:circuits/mv")
.itemInputs("32x gtceu:fine_rhodium_wire")
.itemInputs("kubejs:energy_manager2")
.itemOutputs("ae2:dense_energy_cell")
.EUt(500)
.duration(400)

//CraftingCpu
event.recipes.gtceu.allienassembler("crafting_unit")
.itemInputs("gtceu:fluixsteel_frame")
.itemInputs("kubejs:energy_manager1")
.itemInputs("2x #gtceu:circuits/hv")
.itemInputs("32x gtceu:fluixsteel_foil")
.itemOutputs("ae2:crafting_unit")
.inputFluids("gtceu:aluminium 144")
.EUt(500)
.duration(400)
//CoProzessor
event.recipes.gtceu.assembler("crafting_accelerator")
.itemInputs("ae2:crafting_unit")
.itemInputs("kubejs:energy_manager2")
.itemInputs("32x gtceu:fine_copper_wire")
.itemOutputs("ae2:crafting_accelerator")
.EUt(30)
.duration(200)
//1K-256kCraftingStorage
const Storage = (part, storage, name) => {
event.recipes.gtceu.assembler(`1k_crafting_storage${name}`)
.itemInputs("ae2:crafting_unit")
.itemInputs(part)
.itemOutputs(storage)
.EUt(30)
.duration(200)
}
Storage("ae2:cell_component_1k", "ae2:1k_crafting_storage", 1)
Storage("ae2:cell_component_4k", "ae2:4k_crafting_storage", 4)
Storage("ae2:cell_component_16k", "ae2:16k_crafting_storage", 16)
Storage("ae2:cell_component_64k", "ae2:64k_crafting_storage", 64)
Storage("ae2:cell_component_256k", "ae2:256k_crafting_storage", 256)

//Tier2EnergyManager
event.recipes.gtceu.allienassembler("energy_manager2")
.itemInputs("2x #gtceu:circuits/hv")
.itemInputs("16x gtceu:smd_resistor")
.itemInputs("16x gtceu:smd_inductor")
.itemInputs("gtceu:plastic_printed_circuit_board")
.itemInputs("32x gtceu:fine_steel_wire")
.itemOutputs("kubejs:energy_manager2")
.inputFluids("gtceu:soldering_alloy 288")
.inputFluids("gtceu:non_conducting_glue 288")
.EUt(500)
.duration(400)

//CraftingMonitor
event.recipes.gtceu.assembler("crafting_monitor")
.itemInputs("ae2:crafting_unit")
.itemInputs("gtceu:computer_monitor_cover")
.itemOutputs("4x ae2:crafting_monitor")
.EUt(120)
.duration(200)

//PatternProvider
event.recipes.gtceu.allienassembler("pattern_provider")
.itemInputs("gtceu:certus_quartz_frame")
.itemInputs("ae2:formation_core")
.itemInputs("ae2:annihilation_core")
.itemInputs("#gtceu:circuits/mv")
.itemInputs("8x gtceu:fluixsteel_screw")
.itemOutputs("ae2:pattern_provider")
.inputFluids("gtceu:polyethylene 144")
.EUt(120)
.duration(200)

//Interface
event.recipes.gtceu.allienassembler("interface")
.itemInputs("gtceu:certus_quartz_frame")
.itemInputs("ae2:formation_core")
.itemInputs("ae2:annihilation_core")
.itemInputs("#gtceu:circuits/lv")
.itemInputs("4x gtceu:fluixsteel_screw")
.itemOutputs("ae2:interface")
.inputFluids("gtceu:polyethylene 144")
.EUt(120)
.duration(200)

//StorageBus
event.recipes.gtceu.allienassembler("storage_bus")
.itemInputs("ae2:formation_core")
.itemInputs("ae2:annihilation_core")
.itemInputs("2x ae2:fluix_glass_cable")
.itemInputs("4x gtceu:certus_quartz_rod")
.itemInputs("4x gtceu:fluixsteel_screw")
.itemInputs("#gtceu:circuits/ulv")
.itemOutputs("ae2:storage_bus")
.inputFluids("gtceu:polyethylene 144")
.duration(300)
.EUt(120)

//patternproviderUpgrade
event.recipes.gtceu.allienassembler("pattern_provider_upgrade")
.itemInputs("3x ae2:capacity_card")
.itemInputs("kubejs:energy_manager2")
.itemInputs("gtceu:desh_frame")
.itemInputs("2x #gtceu:circuits/hv")
.itemInputs("16x gtceu:fine_gold_wire")
.itemOutputs("expatternprovider:pattern_provider_upgrade")
.EUt(500)
.duration(400)

//Interfaceupgrade
event.recipes.gtceu.allienassembler("interface_upgrade")
.itemInputs("3x ae2:capacity_card")
.itemInputs("kubejs:energy_manager2")
.itemInputs("gtceu:desh_frame")
.itemInputs("2x #gtceu:circuits/hv")
.itemInputs('16x gtceu:fine_silver_wire')
.itemOutputs('expatternprovider:interface_upgrade')
.EUt(500)
.duration(400)

//TagBus
event.recipes.gtceu.assembler("tag_storage_bus")
.itemInputs("ae2:storage_bus")
.itemInputs("gtceu:item_filter")
.itemInputs("gtceu:fluid_filter")
.itemOutputs("expatternprovider:tag_storage_bus")
.EUt(120)
.duration(300)

//MolecularAssembler
event.recipes.gtceu.allienassembler("molecular_assembler")
.itemInputs("minecraft:crafting_table")
.itemInputs("4x gtceu:mv_robot_arm")
.itemInputs("kubejs:energy_manager2")
.itemInputs("2x #gtceu:circuits/hv")
.itemInputs("2x gtceu:desh_frame")
.itemInputs("6x minecraft:glass_pane")
.itemOutputs("ae2:molecular_assembler")
.inputFluids("gtceu:soldering_alloy 144")
.inputFluids("gtceu:advanced_glue 200")
.EUt(500)
.duration(300)

//Buffer
event.recipes.gtceu.allienassembler("ingredient_buffer")
.itemInputs("2x gtceu:desh_frame")
.itemInputs("gtceu:steel_drum")
.itemInputs("gtceu:steel_crate")
.itemInputs("2x gtceu:mv_conveyor_module")
.itemInputs("2x gtceu:mv_electric_pump")
.itemOutputs("expatternprovider:ingredient_buffer")
.inputFluids("gtceu:polyethylene 576")
.EUt(500)
.duration(300)

//IoPort
event.recipes.gtceu.assembler("io_port")
.itemInputs("2x ae2:chest")
.itemInputs("2x ae2:calculation_processor")
.itemInputs("4x ae2:fluix_glass_cable")
.itemInputs("gtceu:computer_monitor_cover")
.itemInputs("16x gtceu:fine_platinum_wire")
.itemOutputs("ae2:io_port")
.duration(300)
.EUt(120)

//InExport
event.recipes.gtceu.allienassembler("export_bus")
.itemInputs("ae2:formation_core")
.itemInputs("4x ae2:fluix_glass_cable")
.itemInputs("gtceu:lv_electric_piston")
.itemOutputs("4x ae2:export_bus")
.inputFluids("gtceu:polyethylene 288")
.duration(120)
.EUt(30)
event.recipes.gtceu.allienassembler("import_bus")
.itemInputs("ae2:annihilation_core")
.itemInputs("4x ae2:fluix_glass_cable")
.itemInputs("gtceu:lv_electric_piston")
.itemOutputs("4x ae2:import_bus")
.inputFluids("gtceu:polyethylene 288")
.duration(120)
.EUt(30)




//Remove
const remove = (item) => {
event.remove({output:item})
}
remove("ae2:spatial_pylon")
remove("ae2:spatial_io_port")
remove("ae2:spatial_anchor")
remove("ae2:condenser")
remove("ae2:crystal_resonance_generator")
remove("ae2:vibration_chamber")
remove("ae2:1k_crafting_storage")
remove("ae2:4k_crafting_storage")
remove("ae2:16k_crafting_storage")
remove("ae2:64k_crafting_storage")
remove("ae2:256k_crafting_storage")
remove("ae2:crafting_unit")
remove("ae2:crafting_accelerator")
remove("ae2:dense_energy_cell")
remove("ae2:energy_cell")
remove("ae2:energy_acceptor")
remove("ae2:cell_workbench")
remove("ae2:chest")
remove("ae2:drive")
remove("ae2:controller")
remove("ae2:crafting_monitor")
remove("ae2:molecular_assembler")
remove("ae2:growth_accelerator")
remove("ae2:inscriber")
remove("ae2:io_port")
remove("ae2:import_bus")
remove("ae2:export_bus")





event.remove({id:"ae2:network/blocks/pattern_providers_interface"})
event.remove({id:"ae2:network/blocks/interfaces_interface"})
event.remove({id:"ae2:network/parts/storage_bus"})



})