ServerEvents.recipes(event => {

//EnergyManager1 Cheap
event.recipes.gtceu.allienassembler("EnergyManager2")
.itemInputs("8x gtceu:resistor")
.itemInputs("8x gtceu:fine_tantalum_wire")
.itemInputs("4x gtceu:capacitor")
.itemInputs("#gtceu:circuits/mv")
.itemInputs("gtceu:plastic_printed_circuit_board")
.itemOutputs("kubejs:energy_manager1")
.inputFluids("gtceu:soldering_alloy 72")
.EUt(120)
.duration(200)

//Prozessors
const prozessor = (printed, finishedcircuite, name) => {

event.recipes.gtceu.allienassembler(`logic_processor${name}`)
.itemInputs("8x gtceu:fine_annealed_copper_wire")
.itemInputs('4x gtceu:certus_quartz_bolt')
.itemInputs(printed)
.itemInputs("ae2:printed_silicon")
.itemOutputs(finishedcircuite)
.inputFluids("gtceu:soldering_alloy 72")
.inputFluids("gtceu:red_alloy 144")
.EUt(120)
.duration(200)
}
prozessor('ae2:printed_calculation_processor','ae2:calculation_processor' ,"calculation")
prozessor('ae2:printed_engineering_processor','ae2:engineering_processor' ,"engineering")
prozessor('ae2:printed_logic_processor', 'ae2:logic_processor' ,"logic")

//Cores
event.recipes.gtceu.allienassembler("annihalitioncore")
.itemInputs("#gtceu:circuits/lv")
.itemInputs("gtceu:lv_voltage_coil")
.itemInputs("8x gtceu:fine_red_alloy_wire")
.itemInputs("8x gtceu:fine_steel_wire")
.itemOutputs("2x ae2:annihilation_core")
.inputFluids("gtceu:soldering_alloy 72")
.EUt(120)
.duration(200)
event.recipes.gtceu.allienassembler("formationcore")
.itemInputs("#gtceu:circuits/lv")
.itemInputs("gtceu:lv_voltage_coil")
.itemInputs("8x gtceu:fine_red_alloy_wire")
.itemInputs("8x gtceu:fine_aluminium_wire")
.itemOutputs("2x ae2:formation_core")
.inputFluids("gtceu:soldering_alloy 72")
.EUt(120)
.duration(200)

//StoragCell
event.recipes.gtceu.allienassembler("1kStorageCell")
.itemInputs("#gtceu:circuits/lv")
.itemInputs("8x gtceu:fine_copper_wire")
.itemInputs("4x ae2:fluix_crystal")
.itemInputs("2x gtceu:aluminium_plate")
.itemOutputs("ae2:cell_component_1k")
.inputFluids("gtceu:soldering_alloy 72")
.inputFluids("gtceu:red_alloy 144")
.inputFluids("gtceu:steel 288")
.EUt(30)
.duration(200)
event.recipes.gtceu.allienassembler("4kStorageCell")
.itemInputs("#gtceu:circuits/mv")
.itemInputs("32x gtceu:fine_annealed_copper_wire")
.itemInputs("16x ae2:fluix_crystal")
.itemInputs("2x gtceu:stainless_steel_plate")
.itemOutputs("ae2:cell_component_4k")
.inputFluids("gtceu:soldering_alloy 144")
.inputFluids("gtceu:red_alloy 288")
.inputFluids("gtceu:aluminium 576")
.EUt(120)
.duration(200)
event.recipes.gtceu.allienassembler("16kStorageCell")
.itemInputs("2x #gtceu:circuits/hv")
.itemInputs("48x gtceu:fine_tantalum_wire")
.itemInputs("32x ae2:fluix_crystal")
.itemInputs("4x gtceu:double_titanium_plate")
.itemInputs("32x gtceu:polyvinyl_chloride_foil")
.itemOutputs("ae2:cell_component_16k")
.inputFluids("gtceu:soldering_alloy 288")
.inputFluids("gtceu:red_alloy 576")
.inputFluids("gtceu:stainless_steel 1440")
.EUt(500)
.duration(200)
event.recipes.gtceu.allienassembler("64kStorageCell")
.itemInputs("4x #gtceu:circuits/iv")
.itemInputs("64x gtceu:fine_palladium_wire")
.itemInputs("64x gtceu:fine_palladium_wire")
.itemInputs("8x gtceu:double_tungsten_steel_plate")
.itemInputs("64x ae2:fluix_crystal")
.itemInputs("64x gtceu:polytetrafluoroethylene_foil")
.itemOutputs("ae2:cell_component_64k")
.inputFluids("gtceu:soldering_alloy 576")
.inputFluids("gtceu:red_alloy 1440")
.inputFluids("gtceu:titanium 2880")
.EUt(2000)
.duration(200)
event.recipes.gtceu.allienassembler("256kStorageCell")
.itemInputs("6x #gtceu:circuits/luv")
.itemInputs("64x gtceu:fine_naquadah_wire")
.itemInputs("64x gtceu:fine_naquadah_wire")
.itemInputs("16x gtceu:double_rhodium_plated_palladium_plate")
.itemInputs("16x ae2:fluix_block")
.itemInputs("64x gtceu:polybenzimidazole_foil")
.itemOutputs("ae2:cell_component_256k")
.inputFluids("gtceu:soldering_alloy 1440")
.inputFluids("gtceu:platinum 576")
.inputFluids("gtceu:tungsten_steel 5760")
.EUt(8000)
.duration(200)

//CellHosuing
const Cell = (frame, plate, sheet ,EUt ,ammount) => {
event.recipes.gtceu.assembler(`CellHousing${ammount}`)
.itemInputs(frame)
.itemInputs(`2x ${plate}`)
.itemInputs(`4x ${sheet}`)
.itemOutputs(`${ammount} ae2:item_cell_housing`)
.EUt(EUt)
.duration(100)
}
Cell('gtceu:steel_frame', 'gtceu:steel_plate', 'gtceu:polyethylene_foil' ,30 , "1x")
Cell('gtceu:aluminium_frame', 'gtceu:aluminium_plate', 'gtceu:polyvinyl_chloride_foil',120, "2x")
Cell('gtceu:stainless_steel_frame', 'gtceu:stainless_steel_plate', 'gtceu:polytetrafluoroethylene_foil',500 ,"4x")
Cell('gtceu:titanium_frame', 'gtceu:titanium_plate', 'gtceu:polybenzimidazole_foil',2000 ,"8x")

//CellHosuingFluid
const CellFluid = (frame, plate, sheet ,EUt ,ammount ,pump) => {
event.recipes.gtceu.assembler(`FluidCellHousing${ammount}`)
.itemInputs(frame)
.itemInputs(pump)
.itemInputs(`2x ${plate}`)
.itemInputs(`4x ${sheet}`)
.itemOutputs(`${ammount} ae2:fluid_cell_housing`)
.EUt(EUt)
.duration(100)
}
CellFluid('gtceu:steel_frame', 'gtceu:steel_plate', 'gtceu:rubber_foil' ,30 , "1x" ,'gtceu:lv_electric_pump')
CellFluid('gtceu:aluminium_frame', 'gtceu:aluminium_plate', 'gtceu:rubber_foil',120, "2x" ,'gtceu:mv_electric_pump')
CellFluid('gtceu:stainless_steel_frame', 'gtceu:stainless_steel_plate', 'gtceu:silicone_rubber_foil',500 ,"4x" ,'gtceu:hv_electric_pump')
CellFluid('gtceu:titanium_frame', 'gtceu:titanium_plate', 'gtceu:styrene_butadiene_rubber_foil',2000 ,"8x" ,'gtceu:ev_electric_pump')

//PrintedCircuits
const Printed = (press, plate, printed, name) => {
event.recipes.gtceu.forming_press(name)
.notConsumable(press)
.itemInputs(plate)
.itemOutputs(printed)
.duration(200)
.EUt(120)
}
Printed('ae2:calculation_processor_press','gtceu:certus_quartz_plate' ,'ae2:printed_calculation_processor' ,"calculation_processor" )
Printed('ae2:engineering_processor_press','gtceu:diamond_plate' ,'ae2:printed_engineering_processor' ,"engineering_processor")
Printed('ae2:logic_processor_press','create:golden_sheet' ,'ae2:printed_logic_processor' ,"logic_processor")
Printed('ae2:silicon_press','gtceu:silicon_plate' ,'ae2:printed_silicon' ,"printed_silicon")

//WirlessTransiver
event.recipes.gtceu.allienassembler("wirlessresiver")
.itemInputs("4x gtceu:electrum_single_cable")
.itemInputs("2x #gtceu:circuits/hv")
.itemInputs("2x gtceu:fluixsteel_rod")
.itemInputs("gtceu:ev_emitter")
.itemInputs("gtceu:ev_sensor")
.itemInputs("ae2:fluix_pearl")
.itemOutputs("ae2:wireless_receiver")
.inputFluids("gtceu:soldering_alloy 144")
.inputFluids("gtceu:advanced_glue 200")
.EUt(500)
.duration(400)

//FluixCrystal
event.recipes.gtceu.mixer("FluixCrystal")
.itemInputs("8x gtceu:certus_quartz_dust")
.itemInputs("4x minecraft:redstone")
.itemInputs("4x minecraft:glowstone_dust")
.itemOutputs("16x ae2:fluix_dust")
.inputFluids("minecraft:water 144")
.circuit(1)
.EUt(120)
.duration(200)

//FluixPear
event.recipes.gtceu.large_chemical_reactor("FluixPearl")
.itemInputs("gtceu:quantum_eye")
.itemInputs("4x ae2:fluix_dust")
.itemInputs("4x minecraft:glowstone_dust")
.itemOutputs("ae2:fluix_pearl")
.inputFluids("gtceu:distilled_water 576")
.inputFluids("gtceu:acetone 288")
.EUt(500)
.duration(500)

//Cards
//Blank
event.recipes.gtceu.assembler("basic_card")
.itemInputs("ae2:calculation_processor")
.itemInputs("2x gtceu:double_aluminium_plate")
.itemInputs("4x gtceu:fine_electrum_wire")
.itemInputs("#gtceu:circuits/lv")
.itemOutputs("4x ae2:basic_card")
.inputFluids("gtceu:polyethylene 288")
.duration(200)
.EUt(120)
event.recipes.gtceu.assembler("advanced_card")
.itemInputs("ae2:calculation_processor")
.itemInputs("4x gtceu:double_aluminium_plate")
.itemInputs("8x gtceu:fine_aluminium_wire")
.itemInputs("#gtceu:circuits/mv")
.itemOutputs("4x ae2:advanced_card")
.inputFluids("gtceu:polyethylene 288")
.duration(200)
.EUt(500)
//basic
event.recipes.gtceu.assembler("void_card")
.itemInputs("ae2:basic_card")
.itemInputs("#gtceu:circuits/ulv")
.itemInputs("trashcans:item_trash_can")
.itemInputs("trashcans:liquid_trash_can")
.itemInputs("8x gtceu:fine_red_alloy_wire")
.itemOutputs("ae2:void_card")
.duration(300)
.EUt(30)
event.recipes.gtceu.assembler("redstone_card")
.itemInputs("ae2:basic_card")
.itemInputs("#gtceu:circuits/ulv")
.itemInputs("minecraft:comparator")
.itemInputs("8x gtceu:fine_red_alloy_wire")
.itemOutputs("ae2:redstone_card")
.EUt(30)
.duration(300)
event.recipes.gtceu.assembler("capacity_card")
.itemInputs("ae2:basic_card")
.itemInputs("2x #gtceu:circuits/ulv")
.itemInputs("2x minecraft:chest")
.itemInputs("8x gtceu:fine_red_alloy_wire")
.itemOutputs("ae2:capacity_card")
.EUt(30)
.duration(300)
event.recipes.gtceu.assembler("crafting_card")
.itemInputs("ae2:basic_card")
.itemInputs("2x #gtceu:circuits/ulv")
.itemInputs("minecraft:crafting_table")
.itemInputs("8x gtceu:fine_red_alloy_wire")
.itemOutputs("ae2:crafting_card")
.EUt(30)
.duration(300)

//advanced
event.recipes.gtceu.assembler("fuzzy_card")
.itemInputs("ae2:advanced_card")
.itemInputs("2x #gtceu:circuits/lv")
.itemInputs("minecraft:white_wool")
.itemInputs("16x gtceu:fine_electrum_wire")
.itemOutputs("ae2:fuzzy_card")
.EUt(120)
.duration(300)
event.recipes.gtceu.assembler("speed_card")
.itemInputs("ae2:advanced_card")
.itemInputs("2x #gtceu:circuits/lv")
.itemInputs("2x gtceu:magnetic_steel_rod")
.itemInputs("16x gtceu:fine_electrum_wire")
.itemInputs("16x gtceu:fine_tantalum_wire")
.itemOutputs("ae2:speed_card")
.EUt(120)
.duration(300)
event.recipes.gtceu.assembler("inverter_card")
.itemInputs("ae2:advanced_card")
.itemInputs("#gtceu:circuits/lv")
.itemInputs("minecraft:redstone_torch")
.itemInputs("16x gtceu:fine_electrum_wire")
.itemOutputs("ae2:inverter_card")
.EUt(120)
.duration(300)
event.recipes.gtceu.assembler("energy_card")
.itemInputs("ae2:advanced_card")
.itemInputs("#gtceu:circuits/lv")
.itemInputs('#gtceu:batteries/lv')
.itemInputs("16x gtceu:fine_electrum_wire")
.itemOutputs("ae2:energy_card")
.EUt(120)
.duration(300)
event.recipes.gtceu.assembler("equal_distribution_card")
.itemInputs("ae2:advanced_card")
.itemInputs("#gtceu:circuits/lv")
.itemInputs("2x minecraft:comparator")
.itemInputs("16x gtceu:fine_electrum_wire")
.itemOutputs("ae2:equal_distribution_card")
.EUt(120)
.duration(300)

//WirlessBoosterCard
event.recipes.gtceu.assembler("wireless_booster")
.itemInputs("ae2:advanced_card")
.itemInputs("gtceu:mv_emitter")
.itemInputs("gtceu:mv_sensor")
.itemInputs("8x gtceu:fine_platinum_wire")
.itemInputs("8x gtceu:fine_red_alloy_wire")
.itemOutputs("ae2:wireless_booster")
.EUt(500)
.duration(300)

//PatternModifier
event.recipes.gtceu.assembler("pattern_modifier")
.itemInputs("ae2:item_cell_housing")
.itemInputs("4x #gtceu:circuits/ulv")
.itemInputs("gtceu:computer_monitor_cover")
.itemInputs("16x gtceu:fine_red_alloy_wire")
.itemOutputs("expatternprovider:pattern_modifier")
.EUt(30)
.duration(300)

//ViewCell
event.recipes.gtceu.assembler("view_cell")
.itemInputs("ae2:item_cell_housing")
.itemInputs("2x gtceu:item_filter")
.itemInputs("2x gtceu:fluid_filter")
.itemOutputs("ae2:view_cell")
.EUt(30)
.duration(300)

//WaterCell
event.recipes.gtceu.allienassembler("infinity_cell")
.itemInputs("ae2:item_cell_housing")
.itemInputs("ae2:cell_component_64k")
.itemInputs("3x gtceu:ev_field_generator")
.itemInputs("64x gtceu:fine_rhodium_wire")
.itemInputs("64x gtceu:fine_indium_tin_barium_titanium_cuprate_wire")
.itemOutputs("expatternprovider:infinity_cell")
.inputFluids("minecraft:water 10000")
.EUt(8000)
.duration(400)

//CobbleCell
event.recipes.gtceu.allienassembler("infinity_cellcobble")
.itemInputs("ae2:item_cell_housing")
.itemInputs("ae2:cell_component_64k")
.itemInputs("3x gtceu:ev_field_generator")
.itemInputs("64x gtceu:fine_rhodium_wire")
.itemInputs("64x gtceu:fine_indium_tin_barium_titanium_cuprate_wire")
.itemOutputs("expatternprovider:infinity_cell")
.inputFluids("minecraft:water 10000")
.inputFluids("minecraft:lava 10000")
.EUt(8000)
.duration(400)

//MenmoryCard
event.recipes.gtceu.assembler("memory_card")
.itemInputs("gtceu:computer_monitor_cover")
.itemInputs("2x #gtceu:circuits/mv")
.itemInputs("ae2:basic_card")
.itemInputs("gtceu:data_stick")
.itemOutputs("ae2:memory_card")
.EUt(30)
.duration(300)

//AdvancedMemory 
event.recipes.gtceu.assembler("advanced_memory_card")
.itemInputs("ae2:memory_card")
.itemInputs("4x #gtceu:circuits/mv")
.itemInputs("2x ae2:logic_processor")
.itemInputs("ae2:network_tool")
.itemInputs("32x gtceu:fine_silver_wire")
.itemOutputs("betterp2p:advanced_memory_card")
.EUt(30)
.duration(300)

//NetworkVisulizer
event.recipes.gtceu.assembler("network_analyser")
.itemInputs("ae2:network_tool")
.itemInputs("gtceu:lv_emitter")
.itemInputs("gtceu:lv_sensor")
.itemInputs("3x #gtceu:circuits/lv")
.itemOutputs("ae2netanalyser:network_analyser")
.EUt(30)
.duration(300)

//WirelessTool
event.recipes.gtceu.assembler("wireless_tool")
.itemInputs("ae2:network_tool")
.itemInputs("ae2:memory_card")
.itemInputs("2x gtceu:mv_emitter")
.itemInputs("3x #gtceu:circuits/lv")
.itemInputs("32x gtceu:fine_electrum_wire")
.itemOutputs("expatternprovider:wireless_tool")
.EUt(30)
.duration(300)

//NetworkWrench
event.recipes.gtceu.assembler("network_tool")
.itemInputs("2x ae2:logic_processor")
.itemInputs("2x #gtceu:circuits/lv")
.itemInputs("2x gtceu:lv_sensor")
.itemInputs("gtceu:computer_monitor_cover")
.itemInputs("ae2:charged_staff")
.itemInputs("64x gtceu:fine_red_alloy_wire")
.itemOutputs("ae2:network_tool")
.EUt(30)
.duration(300)

//Wrenches
event.shaped("ae2:nether_quartz_wrench", [
    "ABA",
    " A ",
    " A "
], {
    A: "minecraft:quartz",
    B: '#gtceu:tools/crafting_hammers'
})
event.shaped("ae2:certus_quartz_wrench", [
    "ABA",
    " A ",
    " A "
], {
    A: "gtceu:certus_quartz_gem",
    B: '#gtceu:tools/crafting_hammers'
})

//Pattern
const Pattern =(plate ,circuite ,wire ,EUt ,name ,ammount) => {
event.recipes.gtceu.assembler(`blank_pattern${name}`)
.itemInputs("minecraft:glass")
.itemInputs(circuite)
.itemInputs(wire)
.itemInputs(plate)
.itemOutputs(`${ammount}x ae2:blank_pattern`)
.duration(200)
.EUt(EUt)
}
Pattern("gtceu:steel_plate" ,"2x #gtceu:circuits/ulv" ,"gtceu:fine_red_alloy_wire" ,30 ,"ulv" ,4)
Pattern("gtceu:aluminium_plate" ,"2x #gtceu:circuits/lv" ,"gtceu:fine_copper_wire" ,120 ,"lv" ,16)
Pattern("gtceu:titanium_plate" ,"2x #gtceu:circuits/mv" ,"gtceu:fine_platinum_wire" ,2000 ,"ev" ,64)

//ChargedStaff
event.recipes.gtceu.assembler("charged_staff")
.itemInputs("2x gtceu:long_stainless_steel_rod")
.itemInputs("gtceu:exquisite_certus_quartz_gem")
.itemInputs("gtceu:energy_crystal")
.itemInputs("2x #gtceu:circuits/mv")
.itemOutputs("ae2:charged_staff")
.duration(400)
.EUt(120)

//EntropyManipulator
event.recipes.gtceu.assembler("entropy_manipulator")
.itemInputs("ae2:charged_staff")
.itemInputs("4x ae2:fluix_crystal")
.itemInputs("4x gtceu:fluixsteel_screw")
.itemInputs("ae2:energy_cell")
.itemInputs("2x #gtceu:circuits/hv")
.itemInputs("4x gtceu:red_alloy_single_cable")
.itemOutputs("ae2:entropy_manipulator")
.duration(500)
.EUt(500)

//ColorAplicator
event.recipes.gtceu.assembler("color_applicator")
.itemInputs("ae2:cell_component_1k")
.itemInputs("2x gtceu:empty_spray_can")
.itemInputs("ae2:formation_core")
.itemInputs("ae2:certus_quartz_wrench")
.itemInputs("2x ae2:logic_processor")
.itemInputs("32x gtceu:fine_annealed_copper_wire")
.itemOutputs("ae2:color_applicator")
.duration(500)
.EUt(120)

//fluixcrystal
event.recipes.gtceu.large_chemical_reactor("fluix_crystal")
.itemInputs("2x ae2:fluix_dust")
.itemInputs("6x minecraft:quartz")
.itemOutputs("8x ae2:fluix_crystal")
.inputFluids("minecraft:water 144")
.duration(200)
.EUt(120)




event.remove({mod:'expatternprovider'})
event.remove({type:'ae2:inscriber'})
event.remove({type:'ae2:charger'})
event.remove({type:'expatternprovider:circuit_cutter'})
//Remove
const remove = (item) => {
event.remove({output:item})
}
remove("ae2:item_cell_housing")
remove("ae2:cell_component_256k")
remove("ae2:cell_component_64k")
remove("ae2:cell_component_16k")
remove("ae2:cell_component_4k")
remove("ae2:cell_component_1k")
remove("ae2:formation_core")
remove("ae2:annihilation_core")
remove('ae2:engineering_processor')
remove('ae2:calculation_processor')
remove('ae2:logic_processor')
remove('ae2:item_cell_housing')
remove('ae2:fluid_cell_housing')
remove('ae2:wireless_receiver')
remove('ae2:fluix_pearl')
remove('ae2:fluix_crystal')
remove('ae2:certus_quartz_crystal')
remove('ae2:charged_certus_quartz_crystal')
remove('ae2:fluix_dust')
remove('ae2:charger')
remove("ae2:equal_distribution_card")
remove("ae2:energy_card")
remove("ae2:inverter_card")
remove("ae2:speed_card")
remove("ae2:fuzzy_card")
remove("ae2:crafting_card")
remove("ae2:capacity_card")
remove("ae2:redstone_card")
remove("ae2:void_card")
remove("ae2:advanced_card")
remove("ae2:basic_card")
remove("ae2:wireless_booster")
remove("ae2:view_cell")
remove('ae2:spatial_storage_cell_2')
remove('ae2:spatial_storage_cell_16')
remove('ae2:spatial_storage_cell_128')
remove('ae2:spatial_cell_component_2')
remove('ae2:spatial_cell_component_16')
remove('ae2:spatial_cell_component_128')
remove("ae2:certus_quartz_wrench")
remove("ae2:nether_quartz_wrench")
remove("ae2:network_tool")
remove("ae2netanalyser:network_analyser")
remove("betterp2p:advanced_memory_card")
remove("ae2:blank_pattern")
remove('ae2:memory_card')
remove('ae2:entropy_manipulator')
remove('ae2:charged_staff')
remove('ae2:color_applicator')



//Remove
const removeid = (item) => {
event.remove({id:item})
}
removeid("ae2:network/cells/fluid_storage_cell_1k")
removeid("ae2:network/cells/item_storage_cell_1k")
removeid("ae2:network/cells/fluid_storage_cell_4k")
removeid("ae2:network/cells/item_storage_cell_4k")
removeid("ae2:network/cells/fluid_storage_cell_16k")
removeid("ae2:network/cells/item_storage_cell_16k")
removeid("ae2:network/cells/fluid_storage_cell_64k")
removeid("ae2:network/cells/item_storage_cell_64k")
removeid("ae2:network/cells/fluid_storage_cell_256k")
removeid("ae2:network/cells/item_storage_cell_256k")


})



