const $SteamMulti = Java.loadClass('com.gregtechceu.gtceu.common.machine.multiblock.steam.SteamParallelMultiblockMachine');
const CoilWorkableElectricMultiblockMachine = Java.loadClass("com.gregtechceu.gtceu.api.machine.multiblock.CoilWorkableElectricMultiblockMachine")
//Extendet_Centrifuge
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('Extended_Centrifuge', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeTypes(['centrifuge'])
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCC', 'CSC', 'CCC')
            .aisle('CCC', 'CGC', 'CCC')            
            .aisle('CCC', 'CGC', 'CCC')
            .aisle('CCC', 'CGC', 'CCC')
            .aisle('CCC', 'CKC', 'CMC')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where('S', Predicates.abilities(PartAbility.MUFFLER))
            .where('G', Predicates.blocks('gtceu:steel_pipe_casing'))
            .where('C', Predicates.blocks(GTBlocks.CASING_STEEL_SOLID.get())
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setExactLimit(1).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1)))
        .build())
        .workableCasingModel(
            "gtceu:block/casings/solid/machine_casing_solid_steel",
            "gtceu:block/multiblock/advanced_processing_array"
        ) 

//ExtendedMacerator
event.create('Extendedmacerator', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeTypes(['macerator'])
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCC', 'CSC', 'CCC')
            .aisle('CFC', 'FGF', 'CFC')            
            .aisle('CFC', 'FGF', 'CFC')
            .aisle('CFC', 'FGF', 'CFC')
            .aisle('CCC', 'CKC', 'CMC')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where('S', Predicates.abilities(PartAbility.MUFFLER))
            .where('G', Predicates.blocks('gtceu:steel_gearbox'))
            .where('F', Predicates.blocks('gtceu:steel_frame'))
            .where('C', Predicates.blocks(GTBlocks.CASING_STEEL_SOLID.get())
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setExactLimit(1).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1)))
        .build())
        .workableCasingModel(
            "gtceu:block/casings/solid/machine_casing_solid_steel",
            "gtceu:block/multiblock/advanced_processing_array"
        ) 
})
//Extendet_Extractor
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('Extended_Extractor', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock('gtceu:heatproof_machine_casing'))
        .recipeTypes(['extractor'])
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCC', 'CGC', 'CGC', 'CCC')
            .aisle('CCC', 'GBG', 'GBG', 'CSC')
            .aisle('CKC', 'CGC', 'CGC', 'CMC')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where('S', Predicates.abilities(PartAbility.MUFFLER))
            .where('G', Predicates.blocks('gtceu:steel_frame'))
            .where('B', Predicates.blocks('gtceu:bronze_pipe_casing'))
            .where('C', Predicates.blocks('gtceu:heatproof_machine_casing')
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setExactLimit(1).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1)))
        .build())
        .workableCasingModel(
            "gtceu:block/casings/solid/machine_casing_heatproof",
            "gtceu:block/multiblock/advanced_processing_array"
        ) 
})//'gtceu:bronze_pipe_casing'

//Extendet_Sifter
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('Wet_Ore_Processor_4000', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock('kubejs:liquid_working_cassing'))
        .recipeTypes(['sifter', "ore_washer", "chemical_bath"])
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCCCC', 'CCSCC', 'CCCCC')
            .aisle('CCCCC', 'CGGGC', 'C   C')
            .aisle('CCCCC', 'CGGGC', 'C   C')
            .aisle('CCCCC', 'CGGGC', 'C   C')
            .aisle('CCCCC', 'CCKCC', 'CCMCC')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where('S', Predicates.abilities(PartAbility.MUFFLER))
            .where('G', Predicates.blocks('gtceu:assembly_line_grating'))
            .where(' ', Predicates.blocks('minecraft:air'))
            .where('C', Predicates.blocks('kubejs:liquid_working_cassing')
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setExactLimit(1).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1)))
        .build())
        .workableCasingModel(
            "kubejs:block/liquid_working_cassing",
            "gtceu:block/multiblock/advanced_processing_array"
        ) 
})

//Extendet_Thermal_Centrefuge
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('Extended_Thermal_Centrefuge', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock('gtceu:clean_machine_casing'))
        .recipeTypes(['thermal_centrifuge'])
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCC', 'CSC', 'CCC')
            .aisle('CGC', 'GPG', 'CGC')
            .aisle('CGC', 'GPG', 'CGC')
            .aisle('CGC', 'GPG', 'CGC')
            .aisle('CCC', 'CKC', 'CMC')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where('S', Predicates.abilities(PartAbility.MUFFLER))
            .where('G', Predicates.blocks('gtceu:cupronickel_coil_block'))
            .where('P', Predicates.blocks('gtceu:steel_pipe_casing'))
            .where('C', Predicates.blocks('gtceu:clean_machine_casing')
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setExactLimit(1).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1)))
        .build())
        .workableCasingModel(
            "gtceu:block/casings/solid/machine_casing_clean_stainless_steel",
            "gtceu:block/multiblock/advanced_processing_array"
        )
})

//Extendet_Electrolyzer
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('Extended_Electrolyzer', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock('gtceu:clean_machine_casing'))
        .recipeTypes(['electrolyzer'])
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCCCC', 'CTCTC', 'CCCCC')
            .aisle('CCCCC', 'TGCGT', 'CTCTC')
            .aisle('CCCCC', 'TG GT', 'CTCTC')
            .aisle('CCCCC', 'TGCGT', 'CTCTC')
            .aisle('CCKCC', 'CTCTC', 'CCMCC')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where('S', Predicates.abilities(PartAbility.MUFFLER))
            .where('G', Predicates.blocks('gtceu:iron_frame'))
            .where(' ', Predicates.blocks('minecraft:air'))
            .where('T', Predicates.blocks('gtceu:tempered_glass'))
            .where('C', Predicates.blocks('gtceu:clean_machine_casing')
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setExactLimit(1).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1)))
        .build())
        .workableCasingModel(
            "gtceu:block/casings/solid/machine_casing_clean_stainless_steel",
            "gtceu:block/multiblock/advanced_processing_array"
        ) 
})//gtceu:tempered_glass

//Extendet_Mixer
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('Mixatron', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock('kubejs:liquid_working_cassing'))
        .recipeTypes("mixer")
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle(' CCC ', ' CGC ', ' CGC ', ' CSC ', '     ')
            .aisle('CCCCC', 'CA AC', 'C   C', 'C S C', '     ')
            .aisle('CCCCC', 'G I G', 'G I G', 'SSISS', '  I  ')
            .aisle('CCCCC', 'CA AC', 'C   C', 'C S C', '     ')
            .aisle(' KCM ', ' CGC ', ' CGC ', ' CSC ', '     ')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where('A', Predicates.blocks('gtceu:aluminium_frame'))
            .where('I', Predicates.blocks('minecraft:iron_block'))
            .where('S', Predicates.blocks('gtceu:steel_frame'))
            .where('G', Predicates.blocks('gtceu:tempered_glass'))
            .where(' ', Predicates.blocks('minecraft:air'))
            .where('C', Predicates.blocks('kubejs:liquid_working_cassing')
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setExactLimit(1).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1)))
        .build())
        .workableCasingModel(
            "kubejs:block/liquid_working_cassing",
            "gtceu:block/multiblock/advanced_processing_array"
        ) 
})

//AreaAqumulatror
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('AreaAqumulator', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeTypes(['liquid_area_acumolator'])
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCC', 'CCC')
            .aisle('GKG', 'GCG')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('G', Predicates.blocks('gtceu:steel_pipe_casing'))
            .where('C', Predicates.blocks(GTBlocks.CASING_STEEL_SOLID.get())
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1)))
        .build())
        .workableCasingModel(
            "gtceu:block/casings/solid/machine_casing_solid_steel",
            "gtceu:block/multiblock/vacuum_freezer"
        ) 
})

//AreaAqumulatror
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('Aquati_Extractor', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeTypes(['aquatic_extractor'])
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('GCG', 'GCG')
            .aisle('CCC', 'CCC')
            .aisle('CCC', 'CCC')
            .aisle('GKG', 'GMG')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where('G', Predicates.blocks('gtceu:steel_pipe_casing'))
            .where('C', Predicates.blocks(GTBlocks.CASING_STEEL_SOLID.get())
                .or(Predicates.autoAbilities(definition.getRecipeTypes())))
        .build())
        .workableCasingModel(
            "gtceu:block/casings/solid/machine_casing_solid_steel",
            "gtceu:block/multiblock/advanced_processing_array"
        ) 
})


//EarlyConcretMixer
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('Concret_Mixer', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock('gtceu:steam_machine_casing'))
        .recipeTypes('mechanicalconcretmixer')
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCC', 'CSC', 'CSC', 'CCC')
            .aisle('CCC', 'SGS', 'SGS', 'CCC')
            .aisle('CKC', 'CSC', 'CSC', 'CCC')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('G', Predicates.blocks('gtceu:bronze_pipe_casing'))
            .where('S', Predicates.blocks('minecraft:glass'))
            .where('C', Predicates.blocks('gtceu:steam_machine_casing')
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1)))
        .build())
        .workableCasingModel(
            "gtceu:block/casings/solid/machine_casing_bronze_plated_bricks",
            "gtceu:block/multiblock/implosion_compressor"
        ) 
})



//VacuumChamber
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('Vacuum_Chamber', 'multiblock')
        .machine((holder) => new $SteamMulti(holder, 4))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('vacuumchamber')
        .recipeModifier(GTRecipeModifiers.OC_PERFECT)
        .appearanceBlock(() => Block.getBlock('gtceu:steam_machine_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('FCF', 'FSF', 'FCF')
            .aisle('CCC', 'CAC', 'CCC')
            .aisle('FKF', 'FSF', 'FCF')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('S', Predicates.blocks('minecraft:glass'))
            .where('F', Predicates.blocks('gtceu:steel_frame'))
            .where('A', Predicates.blocks('gtceu:bronze_pipe_casing'))
            .where('C', Predicates.blocks('gtceu:steam_machine_casing')
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
               .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS))
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
               .or(Predicates.abilities(PartAbility.STEAM))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS))
               .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS)))
        .build())
        .workableCasingModel(
            "gtceu:block/casings/solid/machine_casing_bronze_plated_bricks",
            "gtceu:block/multiblock/implosion_compressor"
        ) 
})

//SteamBath
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('SteamOreWasher', 'multiblock')
        .machine((holder) => new $SteamMulti(holder, 4))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType("ore_washer")
        .recipeModifier((machine, recipe) => $SteamMulti.recipeModifier(machine, recipe), true)
        .appearanceBlock(() => Block.getBlock('gtceu:steam_machine_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCCCC', 'CCCCC', 'CCCCC')
            .aisle('CCCCC', 'CPPPC', 'CAAAC')
            .aisle('CCCCC', 'CPPPC', 'CAAAC')
            .aisle('CCCCC', 'CPPPC', 'CAAAC')
            .aisle('CCCCC', 'CCKCC', 'CCCCC')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('P', Predicates.blocks('gtceu:bronze_pipe_casing'))
            .where('A', Predicates.blocks('minecraft:air'))
            .where('C', Predicates.blocks('gtceu:steam_machine_casing')
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
               .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS))
               .or(Predicates.abilities(PartAbility.STEAM))
               .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS)))
        .build())
        .workableCasingModel(
            "gtceu:block/casings/solid/machine_casing_bronze_plated_bricks",
            "gtceu:block/multiblock/implosion_compressor"
        ) 
})

//ForgeHammer
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('SteamForgeHammer', 'multiblock')
        .machine((holder) => new $SteamMulti(holder, 8))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType("forge_hammer")
        .recipeModifier((machine, recipe) => $SteamMulti.recipeModifier(machine, recipe), true)
        .appearanceBlock(() => Block.getBlock('gtceu:steam_machine_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCC', 'CCC', 'CCC')
            .aisle('CCC', 'C C', 'CCC')
            .aisle('CCC', 'CKC', 'CCC')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.blocks('minecraft:air'))
            .where('C', Predicates.blocks('gtceu:steam_machine_casing')
               .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS))
               .or(Predicates.abilities(PartAbility.STEAM))
               .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS)))
        .build())
        .workableCasingModel(
            "gtceu:block/casings/solid/machine_casing_bronze_plated_bricks",
            "gtceu:block/multiblock/implosion_compressor"
        ) 
})

//PrimitiveAssembler
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('Primitive_Assembler', 'multiblock')
        .machine((holder) => new $SteamMulti(holder, 4))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType("primitiveassembler")
        .recipeModifier(GTRecipeModifiers.OC_PERFECT)
        .appearanceBlock(() => Block.getBlock('gtceu:steam_machine_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('PCCCP', 'PAAAP')
            .aisle('CPCPC', 'AFAFA')
            .aisle('CCPCC', 'AADAA')
            .aisle('CPCPC', 'AFAFA')
            .aisle('PCKCP', 'PAAAP')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('P', Predicates.blocks("gtceu:steel_frame"))
            .where('A', Predicates.any())
            .where('F', Predicates.blocks('create:mechanical_arm'))
            .where('D', Predicates.blocks('create:depot'))
            .where('C', Predicates.blocks('gtceu:steam_machine_casing')
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
               .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS))
               .or(Predicates.abilities(PartAbility.STEAM))
               .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS)))
        .build())
        .workableCasingModel(
            "gtceu:block/casings/solid/machine_casing_bronze_plated_bricks",
            "gtceu:block/multiblock/implosion_compressor"
        ) 
})

//PrecisionAssembler
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('PrecisionAssembler', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock('gtceu:clean_machine_casing'))
        .recipeTypes("precisionassembler")
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('BCCCB', 'B   B', 'B   B', 'B   B', 'BCCCB')
            .aisle('CCCCC', ' GCG ', ' GGG ', ' GCG ', 'CCCCC')
            .aisle('CCFCC', ' CFC ', ' GFG ', ' CFC ', 'CCFCC')
            .aisle('CCCCC', ' GCG ', ' GGG ', ' GCG ', 'CCCCC')
            .aisle('BCKCB', 'B   B', 'B   B', 'B   B', 'BCMCB')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where(' ', Predicates.blocks('minecraft:air'))
            .where('B', Predicates.blocks("gtceu:blue_steel_frame"))
            .where('G', Predicates.blocks('gtceu:tempered_glass'))
            .where('F', Predicates.blocks('gtceu:stainless_steel_gearbox'))
            .where('C', Predicates.blocks('gtceu:clean_machine_casing')
                .or(Predicates.autoAbilities(definition.getRecipeTypes())))
        .build())
        .workableCasingModel(
            "gtceu:block/casings/solid/machine_casing_clean_stainless_steel",
            "gtceu:block/multiblock/advanced_processing_array"
        ) 
})

//WireCurler
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('CoilAssembler', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeTypes("coilasssembler")
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle(' CBC ', ' GBG ', ' GBG ', ' GPG ')
            .aisle('CCCCC', 'G   G', 'G   G', 'G   G')
            .aisle('BCPCB', 'B P B', 'B P B', 'P   P')
            .aisle('CCCCC', 'G   G', 'G   G', 'G   G')
            .aisle(' KBM ', ' GBG ', ' GBG ', ' GPG ')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where(' ', Predicates.blocks('minecraft:air'))
            .where('B', Predicates.blocks("gtceu:black_steel_frame"))
            .where('G', Predicates.blocks('gtceu:tempered_glass'))
            .where('P', Predicates.blocks('gtceu:steel_pipe_casing'))
            .where('C', Predicates.blocks(GTBlocks.CASING_STEEL_SOLID.get())
                .or(Predicates.autoAbilities(definition.getRecipeTypes())))
        .build())
        .workableCasingModel(
            "gtceu:block/casings/solid/machine_casing_solid_steel",
            "gtceu:block/multiblock/advanced_processing_array"
        ) 
})

//SpecialPlantHabitat
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('SpecialPlantHabitat', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock("kubejs:hermeticcasing"))
        .recipeTypes("specialplanthabitat")
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCCCCCC', 'CGGGGGC', 'CGGGGGC', 'CGGGGGC', 'CGGGGGC', 'CGGGGGC', 'CCCCCCC')
            .aisle('CDDDDDC', 'G     G', 'GDDDDDG', 'G     G', 'GDDDDDG', 'G     G', 'CFFFFFC')
            .aisle('CDDDDDC', 'G     G', 'GDDDDDG', 'G     G', 'GDDDDDG', 'G     G', 'CFFFFFC')
            .aisle('CDDDDDC', 'G  Q  G', 'GDDQDDG', 'G  Q  G', 'GDDQDDG', 'G  Q  G', 'CFFFFFC')
            .aisle('CDDDDDC', 'G     G', 'GDDDDDG', 'G     G', 'GDDDDDG', 'G     G', 'CFFFFFC')
            .aisle('CDDDDDC', 'G     G', 'GDDDDDG', 'G     G', 'GDDDDDG', 'G     G', 'CFFFFFC')
            .aisle('CCCKCCC', 'CGGGGGC', 'CGGGGGC', 'CGGGGGC', 'CGGGGGC', 'CGGGGGC', 'CCCMCCC')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where(' ', Predicates.blocks('minecraft:air'))
            .where('Q', Predicates.blocks("gtceu:nether_quartz_frame"))
            .where('D', Predicates.blocks("minecraft:dirt"))
            .where('G', Predicates.blocks('gtceu:tempered_glass'))
            .where('F', Predicates.blocks("gtceu:filter_casing"))
            .where('C', Predicates.blocks("kubejs:hermeticcasing")
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setExactLimit(3))
               .or(Predicates.blocks("gtceu:ulv_input_bus").setExactLimit(1))
               .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setExactLimit(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setExactLimit(2)))
        .build())
        .workableCasingModel(
            "kubejs:block/hermeticcasing",
            "gtceu:block/multiblock/advanced_processing_array"
        ) 
})

//EmAssemblyline
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('Emassemblyline', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock("kubejs:emcassing"))
        .recipeTypes("emassembler")
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("CIC", "CGC", "CCC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "CGC", "CCC")            
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CKC", "CGC", "CMC")
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where('G', Predicates.blocks("gtceu:stainless_steel_gearbox"))
            .where('L', Predicates.blocks('gtceu:laminated_glass'))
            .where('F', Predicates.blocks("gtceu:polytetrafluoroethylene_frame"))
            .where('C', Predicates.blocks('kubejs:emcassing'))
            .where('I', Predicates.blocks('kubejs:emcassing')
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setPreviewCount(1).setExactLimit(1)))
        .build())
        .workableCasingModel(
            "kubejs:block/emcassing",
            "gtceu:block/multiblock/advanced_processing_array"
        ) 
})

//AtuendAssemblylines
GTCEuStartupEvents.registry('gtceu:machine', event => {
//diode
    event.create('Emassemblylinediode', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock("kubejs:emcassing"))
        .recipeTypes("electronicsassemblydiode")
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("CIC", "CGC", "CCC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "LGL", "CFC")            
            .aisle("CIC", "CGC", "CCC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "CGC", "CCC")            
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CKC", "CGC", "CMC")
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where('G', Predicates.blocks("gtceu:stainless_steel_gearbox"))
            .where('L', Predicates.blocks('gtceu:laminated_glass'))
            .where('F', Predicates.blocks("gtceu:polytetrafluoroethylene_frame"))
            .where('C', Predicates.blocks('kubejs:emcassing'))
            .where('I', Predicates.blocks('kubejs:emcassing')
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setPreviewCount(1).setExactLimit(1)))
        .build())
        .workableCasingModel(
            "kubejs:block/emcassing",
            "gtceu:block/multiblock/advanced_processing_array"
        ) 
//transistor
    event.create('Emassemblylinetransistor', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock("kubejs:emcassing"))
        .recipeTypes("electronicsassemblytransistor")
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("CIC", "CGC", "CCC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "LGL", "CFC")            
            .aisle("CIC", "CGC", "CCC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "CGC", "CCC")            
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CKC", "CGC", "CMC")
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where('G', Predicates.blocks("gtceu:stainless_steel_gearbox"))
            .where('L', Predicates.blocks('gtceu:laminated_glass'))
            .where('F', Predicates.blocks("gtceu:polytetrafluoroethylene_frame"))
            .where('C', Predicates.blocks('kubejs:emcassing'))
            .where('I', Predicates.blocks('kubejs:emcassing')
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setPreviewCount(1).setExactLimit(1)))
        .build())
        .workableCasingModel(
            "kubejs:block/emcassing",
            "gtceu:block/multiblock/advanced_processing_array"
        ) 
//resistor
    event.create('Emassemblylineresistor', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock("kubejs:emcassing"))
        .recipeTypes("electronicsassemblyresistor")
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("CIC", "CGC", "CCC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "LGL", "CFC")            
            .aisle("CIC", "CGC", "CCC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "CGC", "CCC")            
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CKC", "CGC", "CMC")
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where('G', Predicates.blocks("gtceu:stainless_steel_gearbox"))
            .where('L', Predicates.blocks('gtceu:laminated_glass'))
            .where('F', Predicates.blocks("gtceu:polytetrafluoroethylene_frame"))
            .where('C', Predicates.blocks('kubejs:emcassing'))
            .where('I', Predicates.blocks('kubejs:emcassing')
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setPreviewCount(1).setExactLimit(1)))
        .build())
        .workableCasingModel(
            "kubejs:block/emcassing",
            "gtceu:block/multiblock/advanced_processing_array"
        ) 
//capacitor
    event.create('Emassemblylinecapacitor', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock("kubejs:emcassing"))
        .recipeTypes("electronicsassemblycapacitor")
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("CIC", "CGC", "CCC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "LGL", "CFC")            
            .aisle("CIC", "CGC", "CCC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "CGC", "CCC")            
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CKC", "CGC", "CMC")
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where('G', Predicates.blocks("gtceu:stainless_steel_gearbox"))
            .where('L', Predicates.blocks('gtceu:laminated_glass'))
            .where('F', Predicates.blocks("gtceu:polytetrafluoroethylene_frame"))
            .where('C', Predicates.blocks('kubejs:emcassing'))
            .where('I', Predicates.blocks('kubejs:emcassing')
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setPreviewCount(1).setExactLimit(1)))
        .build())
        .workableCasingModel(
            "kubejs:block/emcassing",
            "gtceu:block/multiblock/advanced_processing_array"
        )
//inductor
    event.create('Emassemblylineinductor', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock("kubejs:emcassing"))
        .recipeTypes("electronicsassemblyinductor")
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("CIC", "CGC", "CCC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "LGL", "CFC")    
            .aisle("CIC", "CGC", "CCC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "CGC", "CCC")            
            .aisle("CIC", "LGL", "CFC")
            .aisle("CIC", "LGL", "CFC")
            .aisle("CKC", "CGC", "CMC")
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where('G', Predicates.blocks("gtceu:stainless_steel_gearbox"))
            .where('L', Predicates.blocks('gtceu:laminated_glass'))
            .where('F', Predicates.blocks("gtceu:polytetrafluoroethylene_frame"))
            .where('C', Predicates.blocks('kubejs:emcassing'))
            .where('I', Predicates.blocks('kubejs:emcassing')
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setPreviewCount(1).setExactLimit(1)))
        .build())
        .workableCasingModel(
            "kubejs:block/emcassing",
            "gtceu:block/multiblock/advanced_processing_array"
        )

//AlienTechAssemblyline
    event.create('AlienTechAssemblyline', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock('kubejs:cleanpetcasing'))
        .recipeTypes("allienassembler")
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("SCICS", "QCCCQ", " CCC ")
            .aisle(" CIC ", " LGL ", " CFC ")    
            .aisle(" CIC ", " LGL ", " CFC ")
            .aisle(" CIC ", " LGL ", " CFC ")
            .aisle("SCICS", "QCGCQ", " CCC ")
            .aisle(" CIC ", " LGL ", " CFC ")            
            .aisle(" CIC ", " LGL ", " CFC ")
            .aisle(" CIC ", " LGL ", " CFC ")
            .aisle("SCKCS", "QCCCQ", " CMC ")
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where(' ', Predicates.blocks('minecraft:air'))
            .where('S', Predicates.blocks('ae2:smooth_sky_stone_block'))
            .where('Q', Predicates.blocks('gtceu:fluixsteel_frame'))
            .where('G', Predicates.blocks('kubejs:owassemblycasing'))
            .where('L', Predicates.blocks('kubejs:fluixcoil'))
            .where('F', Predicates.blocks('gtceu:certus_quartz_frame'))
            .where('C', Predicates.blocks('kubejs:cleanpetcasing'))
            .where('I', Predicates.blocks('kubejs:cleanpetcasing')
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setPreviewCount(1).setExactLimit(1)))
        .build())
        .workableCasingModel(
            "kubejs:block/cleanpetcasing",
            "gtceu:block/multiblock/advanced_processing_array"
        )

//AlienTechAssemblyline
    event.create('greenhouse', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock('kubejs:hermeticcasing'))
        .recipeTypes(["greenshousetree" ,"greenshouseplants"])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("CCCCC", " CCC ", " CCC ", " CCC ", " LLL ", " LLL ", "     ")
            .aisle("CCCCC", "CGGGC", "C   C", "C   C", "L   L", "L   L", " LLL ")            
            .aisle("CCCCC", "CGGGC", "C   C", "C   C", "L   L", "L   L", " LLL ")
            .aisle("CCCCC", "CGGGC", "C   C", "C   C", "L   L", "L   L", " LLL ")
            .aisle("CCKMC", " CCC ", " CCC ", " CCC ", " LLL ", " LLL ", "     ")
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where(' ', Predicates.blocks('minecraft:air'))
            .where('G', Predicates.blocks('minecraft:dirt'))
            .where('L', Predicates.blocks('gtceu:tempered_glass'))
            .where('C', Predicates.blocks('kubejs:hermeticcasing')
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setPreviewCount(1)))
        .build())
        .workableCasingModel(
            "kubejs:block/hermeticcasing",
            "gtceu:block/multiblock/advanced_processing_array"
        )

//EnergyGenerator
    event.create('MagicGenerator', 'multiblock')
        .generator(true) 
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock('kubejs:magicressistentcasing'))
        .recipeTypes(["sourcegen"])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("GCCC", "GIIC", "GCCC")
            .aisle("GIIC", "GZZI", "GIIC")
            .aisle("GCCC", "GKIC", "GCCC")
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('G', Predicates.blocks('kubejs:magicburnercasing'))
            .where('Z', Predicates.blocks('gtceu:steel_gearbox'))
            .where('C', Predicates.blocks('kubejs:magicressistentcasing'))
            .where('I', Predicates.blocks('kubejs:magicressistentcasing')
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.OUTPUT_ENERGY).setPreviewCount(1).setExactLimit(1))
               .or(Predicates.abilities(PartAbility.MUFFLER).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.MAINTENANCE).setPreviewCount(1)))
        .build())
        .workableCasingModel(
            "kubejs:block/magicressistentcasing",
            "gtceu:block/multiblock/large_chemical_reactor"
        )

//MetaldeformingExtruder v2.8
    event.create('extendedextruder', 'multiblock')
        .machine((holder) => new CoilWorkableElectricMultiblockMachine(holder))
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock('gtceu:heatproof_machine_casing'))
        .recipeTypes(["extruder" ,"forming_press"])
        .recipeModifiers((machine, recipe) => GTRecipeModifiers.pyrolyseOvenOverclock(machine, recipe))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("IC CI", "I   I", "I   I", "I   I", "IC CI")
            .aisle("CCCCC", " WSW ", " WSW ", " WSW ", "CCCCC")
            .aisle("CCCCC", " SZS ", " SZS ", " SZS ", "CCYCC")
            .aisle("CCKCC", " WSW ", " WSW ", " WSW ", "CCMCC")
            .aisle("IC CI", "I   I", "I   I", "I   I", "IC CI")
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('M', Predicates.abilities(PartAbility.MAINTENANCE))
            .where('G', Predicates.blocks('gtceu:heatproof_machine_casing'))
            .where('Z', Predicates.blocks('gtceu:steel_pipe_casing'))
            .where(' ', Predicates.blocks("minecraft:air"))
            .where('I', Predicates.blocks('gtceu:steel_frame'))
            .where('S', Predicates.blocks('gtceu:invar_frame'))
            .where('W', Predicates.heatingCoils())
            .where('Y', Predicates.abilities(PartAbility.MUFFLER))
            .where('C', Predicates.blocks('gtceu:heatproof_machine_casing')
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setPreviewCount(1).setExactLimit(1))
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1)))
        .build())
        .workableCasingModel(
            "gtceu:block/casings/solid/machine_casing_heatproof",
            "gtceu:block/multiblock/advanced_processing_array"
        )

//InfusionAltar
    event.create('Infusionaltar', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock('ars_nouveau:sourcestone_large_bricks'))
        .recipeTypes(["infusionaltar"])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("  AAAAA  ", "  A   A  ", "  B   B  ", "         ")
            .aisle(" AGGGGGA ", " D     D ", " E     E ", " D     D ")
            .aisle("IGGHFHGGI", "A  J J  A", "B       B", "         ")
            .aisle("IGHFFFHGI", "  J   J  ", "         ", "         ")
            .aisle("IGFFHFFGI", "    L    ", "         ", "         ")
            .aisle("IGHFFFHGI", "  J   J  ", "         ", "         ")
            .aisle("IGGHFHGGI", "A  J J  A", "B       B", "         ")
            .aisle(" AGGGGGA ", " D     D ", " E     E ", " D     D ")
            .aisle("  AAKAA  ", "  A   A  ", "  B   B  ", "         ")
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.blocks("minecraft:air"))
            .where('A', Predicates.blocks('ars_nouveau:sourcestone_large_bricks'))
            .where('B', Predicates.blocks('gtceu:gold_frame'))
            .where('D', Predicates.blocks('ars_nouveau:spell_prism'))
            .where('E', Predicates.blocks('ars_nouveau:spell_sensor'))
            .where('F', Predicates.blocks('minecraft:amethyst_block'))
            .where('G', Predicates.blocks('ars_nouveau:sourcestone'))
            .where('H', Predicates.blocks('ars_nouveau:arcane_core'))
            .where('J', Predicates.blocks('ars_nouveau:arcane_pedestal'))
            .where('L', Predicates.blocks('ars_nouveau:enchanting_apparatus'))
            .where('I', Predicates.blocks('ars_nouveau:sourcestone_large_bricks')
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1)))
        .build())
        .workableCasingModel(
            "ars_nouveau:block/sourcestone_large_bricks",
            "gtceu:block/multiblock/advanced_processing_array"
        )


//meteorcatcher
    event.create('MeteroidCatcher', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeTypes(["meteorcatcher"])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("           bbb           ", "                         ", "                         ", "                         ", "                         ", "                         ", "                         ", "                         ", "                         ", "                         ")
            .aisle("          bcccb          ", "           ccc           ", "           ccc           ", "           ccc           ", "           ccc           ", "           ccc           ", "           ccc           ", "           ccc           ", "        dddcccddd        ", "                         ")
            .aisle("    bb    bcccb    bb    ", "           ccc           ", "           ccc           ", "           ccc           ", "           ccc           ", "           ccc           ", "        dddcccddd        ", "           ccc           ", "     ddd   ccc   ddd     ", "                         ")
            .aisle("   bccb   bcccb   bccb   ", "    cc     ccc     cc    ", "    cc     ccc     cc    ", "    cc     ccc     cc    ", "    cc   bbbbbbb   cc    ", "    cc             cc    ", "    ccddd       dddcc    ", "    cc             cc    ", "    cc             cc    ", "    c               c    ")
            .aisle("  bccccb   bbb   bccccb  ", "   cccc           cccc   ", "   cccc           cccc   ", "   cccc   bbbbb   cccc   ", "   cccbbbb     bbbbccc   ", "   ccc             ccc   ", "   ccc             ccc   ", "   ccc             ccc   ", "   ccc             ccc   ", "   ccc             ccc   ")
            .aisle("  bccccb         bccccb  ", "   cccc           cccc   ", "   cccc           cccc   ", "   cccbbbbdddddbbbbccc   ", "   ccb             bcc   ", "   cc               cc   ", "   cc               cc   ", "   cc               cc   ", "  dcc               ccd  ", "    c               c    ")
            .aisle("   bccb           bccb   ", "    cc             cc    ", "    cc             cc    ", "    cbbdddddddddddbbc    ", "    b               b    ", "                         ", "   d                 d   ", "                         ", "  d                   d  ", "                         ")
            .aisle("    bb             bb    ", "                         ", "                         ", "     bdddbbbbbbbdddb     ", "    b               b    ", "                         ", "   d                 d   ", "                         ", "  d                   d  ", "                         ")
            .aisle("                         ", "                         ", "          bbbbb          ", "     bddbb     bbddb     ", "    b               b    ", "                         ", "  dd                 d   ", "                         ", " d                     d ", "                         ")
            .aisle("                         ", "                         ", "         bbdddbb         ", "     bdbb       bbdb     ", "   bb               bb   ", "                         ", "  d                   d  ", "                         ", " d                     d ", "                         ")
            .aisle(" bbb                 bbb ", "                         ", "        bbdddddbb        ", "    bddb         bddb    ", "   b                 b   ", "                         ", "  d                   d  ", "                         ", " d                     d ", "                         ")
            .aisle("bcccb               bcccb", " ccc       bbb       ccc ", " ccc    bdd   ddb    ccc ", " cccbddb         bddbccc ", " ccb                 bcc ", " cc                   cc ", " cc                   cc ", " cc                   cc ", " cc                   cc ", "                         ")
            .aisle("bcccb               bcccb", " ccc       bbb       ccc ", " ccc    bdd   ddb    ccc ", " cccbddb         bddbccc ", " ccb                 bcc ", " cc                   cc ", " cc                   cc ", " cc                   cc ", " cc                   cc ", "                         ")
            .aisle("bcccb               bcccb", " ccc       bbb       ccc ", " ccc    bdd   ddb    ccc ", " cccbddb         bddbccc ", " ccb                 bcc ", " cc                   cc ", " cc                   cc ", " cc                   cc ", " cc                   cc ", "                         ")
            .aisle(" bbb                 bbb ", "                         ", "        bbdddddbb        ", "    bddb         bddb    ", "   b                 b   ", "                         ", "  d                   d  ", "                         ", " d                     d ", "                         ")
            .aisle("                         ", "                         ", "         bbdddbb         ", "     bdbb       bbdb     ", "   bb               bb   ", "                         ", "  d                   d  ", "                         ", " d                     d ", "                         ")
            .aisle("                         ", "                         ", "          bbbbb          ", "     bddbb     bbddb     ", "    b               b    ", "                         ", "  dd                 d   ", "                         ", " d                     d ", "                         ")
            .aisle("    bb             bb    ", "                         ", "                         ", "     bdddbbbbbbbdddb     ", "    b               b    ", "                         ", "   d                 d   ", "                         ", "  d                   d  ", "                         ")
            .aisle("   bccb           bccb   ", "    cc             cc    ", "    cc             cc    ", "    cbbdddddddddddbbc    ", "    b               b    ", "                         ", "   d                 d   ", "                         ", "  d                   d  ", "                         ")
            .aisle("  bccccb         bccccb  ", "   cccc           cccc   ", "   cccc           cccc   ", "   cccbbbbdddddbbbbccc   ", "   ccb             bcc   ", "   cc               cc   ", "   cc               cc   ", "   cc               cc   ", "  dcc               ccd  ", "    c               c    ")
            .aisle("  bccccb   bbb   bccccb  ", "   cccc           cccc   ", "   cccc           cccc   ", "   cccc   bbbbb   cccc   ", "   cccbbbb     bbbbccc   ", "   ccc             ccc   ", "   ccc             ccc   ", "   ccc             ccc   ", "   ccc             ccc   ", "   ccc             ccc   ")
            .aisle("   bccb   bcccb   bccb   ", "    cc     ccc     cc    ", "    cc     ccc     cc    ", "    cc     ccc     cc    ", "    cc   bbbbbbb   cc    ", "    cc             cc    ", "    ccddd       dddcc    ", "    cc             cc    ", "    cc             cc    ", "    c               c    ")
            .aisle("    bb    bcccb    bb    ", "           ccc           ", "           ccc           ", "           ccc           ", "           ccc           ", "           ccc           ", "        dddcccddd        ", "           ccc           ", "     ddd   ccc   ddd     ", "                         ")
            .aisle("          bcccb          ", "           ccc           ", "           ccc           ", "           ccc           ", "           ccc           ", "           ccc           ", "           ccc           ", "           ccc           ", "        dddcccddd        ", "                         ")
            .aisle("           bKb           ", "                         ", "                         ", "                         ", "                         ", "                         ", "                         ", "                         ", "                         ", "                         ")
                .where('K', Predicates.controller(Predicates.blocks(definition.get())))
                .where(" ", Predicates.blocks("minecraft:air"))
                .where("d", Predicates.blocks("gtceu:steel_frame"))
                .where("c", Predicates.blocks("gtceu:light_concrete"))
                .where("b", Predicates.blocks("gtceu:solid_machine_casing")
                    .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
                    .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setPreviewCount(1).setExactLimit(1))
                    .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
                    .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1)))

        .build())
        .workableCasingModel(
            "gtceu:block/casings/solid/machine_casing_solid_steel",
            "gtceu:block/multiblock/advanced_processing_array"
        )


//MeteorCannon
    event.create('MeteroidCannon', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeTypes(["meteorcannon"])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("  aaaaaaa  ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ")
            .aisle(" aaaaaaaaa ", "    ccc    ", "     c     ", "     c     ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ")
            .aisle("aaaaaaaaaaa", "   ddedd   ", "   ddedd   ", "   ddedd   ", "    dcd    ", "     c     ", "     c     ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ")
            .aisle("aaaaaaaaaaa", "  ddfefdd  ", "  ddfefdd  ", "  ddfefdd  ", "   dfefd   ", "   dfefd   ", "    fef    ", "     c     ", "     c     ", "     c     ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ")
            .aisle("aaaaaaaaaaa", " cdfgggfdc ", "  dfgggfd  ", "  dfgggfd  ", "  dfgggfd  ", "   fgggf   ", "   fgggf   ", "    ggg    ", "    ggg    ", "    ggg    ", "    ggg    ", "    ggg    ", "     g     ", "     g     ", "     g     ", "           ", "           ", "           ", "           ")
            .aisle("aaaaaaaaaaa", " ceeghgeec ", " ceeghgeec ", " ceeghgeec ", "  ceghgec  ", "  ceghgec  ", "  ceghgec  ", "   cghgc   ", "   cghgc   ", "   cghgc   ", "    ghg    ", "    ghg    ", "    ghg    ", "    ghg    ", "    ghg    ", "     h     ", "     h     ", "     h     ", "     h     ")
            .aisle("aaaaaaaaaaa", " cdfgggfdc ", "  dfgggfd  ", "  dfgggfd  ", "  dfgggfd  ", "   fgggf   ", "   fgggf   ", "    ggg    ", "    ggg    ", "    ggg    ", "    ggg    ", "    ggg    ", "     g     ", "     g     ", "     g     ", "           ", "           ", "           ", "           ")
            .aisle("aaaaaaaaaaa", "  ddfefdd  ", "  ddfefdd  ", "  ddfefdd  ", "   dfefd   ", "   dfefd   ", "    fef    ", "     c     ", "     c     ", "     c     ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ")
            .aisle("aaaaaaaaaaa", "   ddedd   ", "   ddedd   ", "   ddedd   ", "    dcd    ", "     c     ", "     c     ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ")
            .aisle(" aaaaaaaaa ", "    ccc    ", "     c     ", "     c     ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ")
            .aisle("  aaaKaaa  ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ")
                .where('K', Predicates.controller(Predicates.blocks(definition.get())))
                .where(" ", Predicates.blocks("minecraft:air"))
                .where("c", Predicates.blocks("gtceu:black_steel_frame"))
                .where("e", Predicates.blocks("gtceu:stainless_steel_gearbox"))
                .where("f", Predicates.blocks("gtceu:stainless_steel_frame"))
                .where("g", Predicates.blocks("gtceu:stress_proof_casing"))
                .where("h", Predicates.blocks("gtceu:tungstensteel_pipe_casing"))
                .where("d", Predicates.blocks("gtceu:stable_machine_casing"))
                .where("a", Predicates.blocks("gtceu:solid_machine_casing")
                    .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
                    .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setPreviewCount(1).setExactLimit(1))
                    .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
                    .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1)))
        .build())
        .workableCasingModel(
            "gtceu:block/casings/solid/machine_casing_solid_steel",
            "gtceu:block/multiblock/advanced_processing_array"
        )
    

//InfusionAltarII
    event.create('Infusionaltar_II', 'multiblock')
        .rotationState(RotationState.ALL)
        .appearanceBlock(() => Block.getBlock('ars_nouveau:sourcestone_large_bricks'))
        .recipeTypes(["infusionaltar"])
        .pattern(definition => FactoryBlockPattern.start()
        .aisle("   bbbbbbbbb   ", "   b  bbb  b   ", "       b       ", "               ", "               ", "               ")
        .aisle("  bdddddddddb  ", "  be  efe  eb  ", "  be  ege  eb  ", "       g       ", "       g       ", "       c       ")
        .aisle(" bdddddddddddb ", " bf         fb ", " bg         gb ", "  g         g  ", "  c         c  ", "               ")
        .aisle("bddddbbbbbddddb", "be   b   b   eb", " e   e   e   e ", "               ", "               ", "               ")
        .aisle("bdddbhhhhhbdddb", "    f     f    ", "    g     g    ", "    f     f    ", "               ", "               ")
        .aisle("bddbhhijihhbddb", "   b  k k  b   ", "   e       e   ", "               ", "               ", "               ")
        .aisle("bddbhijjjihbddb", " e   k   k   eb", " e           e ", "               ", "               ", "               ")
        .aisle("bddbhjjijjhbddb", " f     l     fb", " g           gb", " g           g ", " g           g ", " c           c ")
        .aisle("bddbhijjjihbddb", " e   k   k   eb", " e           e ", "               ", "               ", "               ")
        .aisle("bddbhhijihhbddb", "   b  k k  b   ", "   e       e   ", "               ", "               ", "               ")
        .aisle("bdddbhhhhhbdddb", "    f     f    ", "    g     g    ", "    f     f    ", "               ", "               ")
        .aisle("bddddbbbbbddddb", "be   b   b   eb", " e   e   e   e ", "               ", "               ", "               ")
        .aisle(" bdddddddddddb ", " bf         fb ", " bg         gb ", "  g         g  ", "  c         c  ", "               ")
        .aisle("  bdddddddddb  ", "  be  efe  eb  ", "  be  ege  eb  ", "       g       ", "       g       ", "       c       ")
        .aisle("   bbbbKbbbb   ", "   b  bbb  b   ", "       b       ", "               ", "               ", "               ")

.where(" ", Predicates.blocks("minecraft:air"))
.where('K', Predicates.controller(Predicates.blocks(definition.get())))
.where("b", Predicates.blocks("ars_nouveau:sourcestone_large_bricks")
               .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
               .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1)))
.where("c", Predicates.blocks("ars_nouveau:void_prism"))
.where("d", Predicates.blocks("ars_nouveau:smooth_sourcestone"))
.where("e", Predicates.blocks("gtceu:gold_frame"))
.where("f", Predicates.blocks("ars_nouveau:spell_prism"))
.where("g", Predicates.blocks("ars_nouveau:spell_sensor"))
.where("h", Predicates.blocks("ars_nouveau:sourcestone"))
.where("i", Predicates.blocks("ars_nouveau:arcane_core"))
.where("j", Predicates.blocks("minecraft:amethyst_block"))
.where("k", Predicates.blocks("ars_nouveau:arcane_pedestal"))
.where("l", Predicates.blocks("ars_nouveau:enchanting_apparatus"))

        .build())
        .workableCasingModel(
            "ars_nouveau:block/sourcestone_large_bricks",
            "gtceu:block/multiblock/advanced_processing_array"
        )
    })
