ServerEvents.recipes(event => {

//ExpensiveSmd
event.recipes.gtceu.emassembler("expensivetransistor1")
.itemInputs("8x kubejs:transistor_chip")
.itemInputs("32x gtceu:fine_platinum_wire")
.itemInputs("32x gtceu:fine_tantalum_wire")
.itemInputs("16x gtceu:fine_red_alloy_wire")
.itemOutputs("gtceu:smd_transistor")
.inputFluids("gtceu:palladium 288")
.inputFluids("gtceu:soldering_alloy 576")
.EUt(500)
.duration(1000)
.cleanroom(CleanroomType.CLEANROOM)
event.recipes.gtceu.emassembler("expensiveresistor2")
.itemInputs("16x gtceu:activated_carbon_dust")
.itemInputs("8x gtceu:silicon_plate")
.itemInputs("64x gtceu:fine_annealed_copper_wire")
.itemInputs("32x gtceu:fine_tantalum_wire")
.itemInputs("16x gtceu:gallium_foil")
.itemOutputs("gtceu:smd_resistor")
.inputFluids("gtceu:soldering_alloy 144")
.EUt(500)
.duration(1000)
.cleanroom(CleanroomType.CLEANROOM)
event.recipes.gtceu.emassembler("expensivecapacitor3")
.itemInputs("32x gtceu:platinum_foil")
.itemInputs("64x gtceu:silicone_rubber_foil")
.itemInputs("16x gtceu:fine_palladium_wire")
.itemInputs("8x gtceu:lithium_dust")
.itemOutputs("gtceu:smd_capacitor")
.inputFluids("gtceu:non_conducting_glue 500")
.inputFluids("gtceu:palladium 144")
.EUt(500)
.duration(1000)
.cleanroom(CleanroomType.CLEANROOM)
event.recipes.gtceu.emassembler("expensivediode4")
.itemInputs("16x kubejs:diode_chip")
.itemInputs("64x gtceu:fine_red_alloy_wire")
.itemInputs("8x gtceu:gallium_arsenide_dust")
.itemInputs("32x gtceu:fine_platinum_wire")
.itemInputs("32x gtceu:tantalum_foil")
.itemOutputs("gtceu:smd_diode")
.inputFluids("gtceu:soldering_alloy 288")
.inputFluids("gtceu:platinum 144")
.EUt(500)
.duration(1000)
.cleanroom(CleanroomType.CLEANROOM)
event.recipes.gtceu.emassembler("expensiveinductor5")
.itemInputs("8x gtceu:nickel_zinc_ferrite_ring")
.itemInputs("4x gtceu:nickel_zinc_ferrite_rod")
.itemInputs("64x gtceu:fine_annealed_copper_wire")
.itemInputs("32x gtceu:fine_platinum_wire")
.itemInputs("16x gtceu:palladium_foil")
.itemOutputs("gtceu:smd_inductor")
.inputFluids("gtceu:soldering_alloy 288")
.inputFluids("gtceu:polyethylene 1440")
.EUt(500)
.duration(1000)
.cleanroom(CleanroomType.CLEANROOM)
//Smd
//Transistor
event.recipes.gtceu.electronicsassemblytransistor("smdtransistor1")
.itemInputs("8x kubejs:transistor_chip")
.itemInputs("2x gtceu:gallium_foil")
.itemInputs("16x gtceu:fine_annealed_copper_wire")
.itemInputs("16x gtceu:fine_red_alloy_wire")
.itemOutputs("16x gtceu:smd_transistor")
.inputFluids("gtceu:advanced_glue 100")
.inputFluids("gtceu:soldering_alloy 72")
.inputFluids("gtceu:polyethylene 72")
.EUt(500)
.duration(200)
.cleanroom(CleanroomType.CLEANROOM)
event.recipes.gtceu.electronicsassemblytransistor("smdtransistor2")
.itemInputs("8x kubejs:transistor_chip")
.itemInputs("2x gtceu:platinum_foil")
.itemInputs("16x gtceu:fine_tantalum_wire")
.itemInputs("16x gtceu:fine_red_alloy_wire")
.itemOutputs("32x gtceu:smd_transistor")
.inputFluids("gtceu:advanced_glue 100")
.inputFluids("gtceu:soldering_alloy 144")
.inputFluids("gtceu:polyethylene 288")
.EUt(500)
.duration(200)
.cleanroom(CleanroomType.CLEANROOM)
//Resistor
event.recipes.gtceu.electronicsassemblyresistor("smdresistor")
.itemInputs("gtceu:carbon_dust")
.itemInputs("8x gtceu:fine_electrum_wire")
.itemInputs("16x gtceu:fine_annealed_copper_wire")
.itemOutputs("16x gtceu:smd_resistor")
.inputFluids("gtceu:advanced_glue 100")
.inputFluids("gtceu:non_conducting_glue 100")
.inputFluids("gtceu:polyethylene 144")
.EUt(500)
.duration(200)
.cleanroom(CleanroomType.CLEANROOM)
event.recipes.gtceu.electronicsassemblyresistor("smdresistor2")
.itemInputs("gtceu:carbon_dust")
.itemInputs("8x gtceu:fine_electrum_wire")
.itemInputs("16x gtceu:fine_tantalum_wire")
.itemOutputs("32x gtceu:smd_resistor")
.inputFluids("gtceu:advanced_glue 100")
.inputFluids("gtceu:non_conducting_glue 100")
.inputFluids("gtceu:polyethylene 144")
.EUt(500)
.duration(200)
.cleanroom(CleanroomType.CLEANROOM)
//Capacitor
event.recipes.gtceu.electronicsassemblycapacitor("smdcapacitor")
.itemInputs("4x gtceu:polyethylene_foil")
.itemInputs("8x gtceu:tantalum_foil")
.itemInputs("16x gtceu:fine_annealed_copper_wire")
.itemOutputs("16x gtceu:smd_capacitor")
.inputFluids("gtceu:non_conducting_glue 144")
.inputFluids("gtceu:advanced_glue 100")
.inputFluids("gtceu:polyethylene 144")
.EUt(500)
.duration(200)
.cleanroom(CleanroomType.CLEANROOM)
event.recipes.gtceu.electronicsassemblycapacitor("smdcapacitor2")
.itemInputs("4x gtceu:polyvinyl_chloride_foil")
.itemInputs("8x gtceu:tantalum_foil")
.itemInputs("16x gtceu:fine_tantalum_wire")
.itemOutputs("24x gtceu:smd_capacitor")
.inputFluids("gtceu:non_conducting_glue 144")
.inputFluids("gtceu:advanced_glue 100")
.inputFluids("gtceu:polyethylene 288")
.EUt(500)
.duration(200)
.cleanroom(CleanroomType.CLEANROOM)
//Diode
event.recipes.gtceu.electronicsassemblydiode("smddiode")
.itemInputs("8x kubejs:diode_chip")
.itemInputs("16x gtceu:fine_red_alloy_wire")
.itemInputs("16x gtceu:fine_annealed_copper_wire")
.itemOutputs("16x gtceu:smd_diode")
.inputFluids("gtceu:advanced_glue 100")
.inputFluids("gtceu:polyethylene 144")
.EUt(500)
.duration(200)
.cleanroom(CleanroomType.CLEANROOM)
event.recipes.gtceu.electronicsassemblydiode("smddiode2")
.itemInputs("8x kubejs:diode_chip")
.itemInputs("16x gtceu:fine_platinum_wire")
.itemInputs("16x gtceu:fine_tantalum_wire")
.itemOutputs("32x gtceu:smd_diode")
.inputFluids("gtceu:advanced_glue 100")
.inputFluids("gtceu:polyethylene 288")
.EUt(500)
.duration(200)
.cleanroom(CleanroomType.CLEANROOM)
//Inductor
event.recipes.gtceu.electronicsassemblyinductor("smd_inductor")
.itemInputs("2x gtceu:nickel_zinc_ferrite_ring")
.itemInputs("64x gtceu:fine_cupronickel_wire")
.itemInputs("8x gtceu:fine_annealed_copper_wire")
.itemOutputs("16x gtceu:smd_inductor")
.inputFluids("gtceu:soldering_alloy 144")
.inputFluids("gtceu:advanced_glue 100")
.inputFluids("gtceu:polyethylene 144")
.EUt(500)
.duration(200)
.cleanroom(CleanroomType.CLEANROOM)
event.recipes.gtceu.electronicsassemblyinductor("smd_inductor2")
.itemInputs("2x gtceu:nickel_zinc_ferrite_ring")
.itemInputs('16x gtceu:fine_platinum_wire')
.itemInputs("8x gtceu:fine_tantalum_wire")
.itemOutputs("32x gtceu:smd_inductor")
.inputFluids("gtceu:soldering_alloy 144")
.inputFluids("gtceu:advanced_glue 100")
.inputFluids("gtceu:polyethylene 288")
.EUt(500)
.duration(200)
.cleanroom(CleanroomType.CLEANROOM)

event.remove({output: "gtceu:smd_inductor"})
event.remove({output: "gtceu:smd_resistor"})
event.remove({output: "gtceu:smd_transistor"})
event.remove({output: "gtceu:smd_diode"})
event.remove({output: "gtceu:smd_capacitor"})
})
