ServerEvents.recipes(event => {

//NickelSilver
event.recipes.gtceu.mixer("nickelsilver")
.itemInputs("5x #forge:dusts/copper")
.itemInputs("3x #forge:dusts/nickel")
.itemInputs("2x gtceu:zinc_dust")
.itemOutputs("10x gtceu:silver_nickle_dust")
.EUt(500)
.duration(200)

//EmCassing
event.recipes.gtceu.precisionassembler("emcassing")
.itemInputs("6x gtceu:red_steel_plate")
.itemInputs("4x gtceu:silver_nickle_foil")
.itemInputs("gtceu:steel_frame")
.itemOutputs("2x kubejs:emcassing")
.inputFluids("gtceu:polyvinyl_chloride 144")
.inputFluids("gtceu:soldering_alloy 72")
.EUt(500)
.duration(200)

//EMAssemblyline
event.recipes.gtceu.precisionassembler("emassemblyline")
.itemInputs("2x kubejs:emcassing")
.itemInputs("6x gtceu:hv_robot_arm")
.itemInputs("2x gtceu:hv_conveyor_module")
.itemInputs("2x gtceu:polytetrafluoroethylene_frame")
.itemInputs("32x gtceu:silver_nickle_foil")
.itemOutputs("gtceu:emassemblyline")
.inputFluids("gtceu:soldering_alloy 288")
.inputFluids("gtceu:polyethylene 576")
.EUt(500)
.duration(400)

//AdvancedGlue
event.recipes.gtceu.mixer("advancedglue")
.inputFluids("gtceu:epoxy 100")
.inputFluids("gtceu:diethylenetriamine 100")
.outputFluids("gtceu:advanced_glue 200")
.EUt(120)
.duration(200)

//AdAstra
event.recipes.gtceu.mixer("aluminiumlithiumalloy")
.itemInputs("17x gtceu:aluminium_dust")
.itemInputs("2x gtceu:lithium_dust")
.itemInputs('#forge:dusts/silver')
.itemOutputs("20x gtceu:aluminiumlithium_dust")
.EUt(120)
.duration(200)

//Tier1RocketParts
//RocketNose
event.recipes.gtceu.precisionassembler("RocketNose")
.itemInputs("4x gtceu:double_aluminiumlithium_plate")
.itemInputs("2x gtceu:steel_screw")
.itemInputs("2x gtceu:steel_screw")
.itemInputs('#gtceu:circuits/mv')
.itemInputs('gtceu:mv_emitter')
.itemInputs('gtceu:mv_sensor')
.itemOutputs("ad_astra:rocket_nose_cone")
.EUt(500)
.duration(200)
//RocketFin
event.recipes.gtceu.precisionassembler("Tier1RocketFin")
.itemInputs("2x gtceu:double_aluminiumlithium_plate")
.itemInputs("gtceu:aluminiumlithium_plate")
.itemInputs("4x gtceu:steel_screw")
.itemOutputs("ad_astra:rocket_fin")
.EUt(500)
.duration(200)
//SteelTank
event.recipes.gtceu.precisionassembler("Tier1SteelTank")
.itemInputs("gtceu:steel_drum")
.itemInputs("2x gtceu:rubber_ring")
.itemInputs("2x gtceu:steel_small_fluid_pipe")
.itemOutputs("ad_astra:steel_tank")
.inputFluids("gtceu:non_conducting_glue 288")
.EUt(500)
.duration(200)
//RocketEngine
event.recipes.gtceu.assembler("Tier1SteelEngine")
.itemInputs("2x ad_astra:steel_tank")
.itemInputs("4x gtceu:double_aluminiumlithium_plate")
.itemInputs("8x gtceu:steel_screw")
.itemInputs("2x gtceu:aluminium_frame")
.itemInputs("2x gtceu:aluminiumlithium_plate")
.itemInputs('2x #gtceu:circuits/hv')
.itemOutputs("ad_astra:steel_engine")
.inputFluids("gtceu:aluminium 576")
.inputFluids("gtceu:lubricant 288")
.EUt(500)
.duration(200)
//Rocket
event.recipes.gtceu.precisionassembler("Tier1Rocket")
.itemInputs("ad_astra:rocket_nose_cone")
.itemInputs("16x gtceu:double_aluminiumlithium_plate")
.itemInputs("4x ad_astra:rocket_fin")
.itemInputs("2x ad_astra:steel_engine")
.itemInputs("16x gtceu:steel_screw")
.itemInputs("2x gtceu:hv_emitter")
.itemInputs("2x gtceu:hv_sensor")
.itemInputs('2x #gtceu:circuits/ev')
.itemOutputs("ad_astra:tier_1_rocket")
.inputFluids("gtceu:aluminium 576")
.EUt(500)
.duration(200)
//GasTankTier1
event.recipes.gtceu.assembler("GasTankTier1")
.itemInputs("ad_astra:steel_tank")
.itemInputs("gtceu:lv_electric_pump")
.itemInputs("4x gtceu:rubber_ring")
.itemInputs("gtceu:polyethylene_tiny_fluid_pipe")
.itemOutputs("ad_astra:gas_tank")
.EUt(120)
.duration(400)
//GasTankTier2
event.recipes.gtceu.assembler("largegastank")
.itemInputs("2x ad_astra:gas_tank")
.itemInputs("gtceu:lv_electric_pump")
.itemInputs("8x gtceu:rubber_ring")
.itemInputs("2x gtceu:polyethylene_tiny_fluid_pipe")
.itemInputs("2x gtceu:steel_frame")
.itemOutputs('ad_astra:large_gas_tank')
.EUt(120)
.duration(400)
//LandingPat
event.recipes.gtceu.assembler("LandingPat")
.itemInputs("8x gtceu:steel_rod")
.itemInputs("4x gtceu:steel_plate")
.itemOutputs("ad_astra:launch_pad")
.inputFluids("gtceu:concrete 1440")
.EUt(120)
.duration(800)
//SpaceSuiteHat
event.recipes.gtceu.assembler("SpaceSuiteHat")
.itemInputs("gtceu:steel_helmet")
.itemInputs("32x gtceu:polyethylene_foil")
.itemInputs("5x minecraft:white_wool")
.itemInputs("5x minecraft:glass_pane")
.itemInputs("2x #gtceu:circuits/lv")
.itemInputs("gtceu:lv_sensor")
.itemOutputs("ad_astra:space_helmet")
.EUt(120)
.duration(800)
//SpaceSuiteChestplate
event.recipes.gtceu.assembler("SpaceSuiteChestplate")
.itemInputs("gtceu:steel_chestplate")
.itemInputs("8x gtceu:polyethylene_plate")
.itemInputs("32x gtceu:polyethylene_foil")
.itemInputs("ad_astra:oxygen_gear")
.itemInputs("8x minecraft:white_wool")
.itemOutputs("ad_astra:space_suit")
.EUt(120)
.duration(800)
//SpaceSuiteLeggins
event.recipes.gtceu.assembler("SpaceSuiteLeggings")
.itemInputs("gtceu:steel_leggings")
.itemInputs("4x gtceu:polyethylene_plate")
.itemInputs("32x gtceu:polyethylene_foil")
.itemInputs("7x minecraft:white_wool")
.itemOutputs("ad_astra:space_pants")
.EUt(120)
.duration(800)
//SpaceSuiteBoots
event.recipes.gtceu.assembler("SpaceSuiteBoots")
.itemInputs("gtceu:steel_boots")
.itemInputs("32x gtceu:polyethylene_foil")
.itemInputs("4x minecraft:white_wool")
.itemInputs("2x gtceu:steel_plate")
.itemOutputs("ad_astra:space_boots")
.EUt(120)
.duration(800)
//OxygenGear
event.recipes.gtceu.assembler("OxygenGear")
.itemInputs("2x ad_astra:gas_tank")
.itemInputs("gtceu:aluminium_frame")
.itemInputs("2x gtceu:lv_electric_pump")
.itemInputs("32x gtceu:polyethylene_foil")
.itemInputs("4x gtceu:polyethylene_tiny_fluid_pipe")
.itemInputs("8x gtceu:rubber_ring")
.itemOutputs("ad_astra:oxygen_gear")
.EUt(120)
.duration(800)

//MoonDustLine
//Dust
event.recipes.gtceu.macerator("moondust1")
.itemInputs("ad_astra:moon_sand")
.itemOutputs("gtceu:lunardust_dust")
.EUt(30)
.duration(100)
event.recipes.gtceu.macerator("moondust2")
.itemInputs("ad_astra:moon_stone")
.itemOutputs("2x gtceu:lunardust_dust")
.EUt(30)
.duration(100)
event.recipes.gtceu.macerator("moondust3")
.itemInputs("ad_astra:moon_deepslate")
.itemOutputs("4x gtceu:lunardust_dust")
.EUt(30)
.duration(100)
//AlternateDustCentrifuge
event.recipes.gtceu.centrifuge("stone_dust")
.itemInputs("32x gtceu:lunardust_dust")
.itemOutputs("16x gtceu:stone_dust")
.chancedOutput("8x gtceu:impure_aluminium_dust", 3500 , 1000)
.chancedOutput("4x gtceu:impure_bauxite_dust", 3000 ,1000)
.chancedOutput("2x gtceu:impure_tantalite_dust", 2000 ,1000)
.chancedOutput("8x ad_astra:ice_shard", 5000 ,1000)
.duration(400)
.EUt(120)
//Slurry
event.recipes.gtceu.mixer("lunardustslurry")
.itemInputs("32x gtceu:lunardust_dust")
.inputFluids("gtceu:distilled_water 2000")
.outputFluids("gtceu:lunardustslurry 2000")
.EUt(120)
.duration(200)
//PuriefiedDust
event.recipes.gtceu.centrifuge("SlurryCnetrifuging")
.itemOutputs("16x gtceu:purifiedlunardust_dust")
.itemOutputs("8x gtceu:stone_dust")
.itemOutputs("3x ae2:sky_dust")
.chancedOutput("3x gtceu:impure_aluminium_dust" ,3000 ,1000)
.chancedOutput("2x gtceu:impure_bauxite_dust" ,2000 ,500 )
.chancedOutput('gtceu:impure_scheelite_dust', 1000 ,1000)
.inputFluids("gtceu:lunardustslurry 1000")
.outputFluids("minecraft:water 500")
.EUt(500)
.duration(200)
//EndResult
event.recipes.gtceu.centrifuge("PurifiedCnetrifuging")
.itemInputs("8x gtceu:purifiedlunardust_dust")
.itemOutputs("4x ae2:sky_dust")
.chancedOutput("ae2:fluix_dust" ,5000 ,1000)
.chancedOutput('gtceu:impure_scheelite_dust', 1000 ,1000)
.chancedOutput("gtceu:impure_ilmenite_dust" ,1000, 1000)
.chancedOutput("gtceu:ilmenite_slag_dust" ,500 ,200)
.EUt(500)
.duration(400)

//ESCoil
event.recipes.gtceu.precisionassembler("ESCoils")
.itemInputs("32x gtceu:fluixsteel_foil")
.itemInputs("8x ae2:fluix_dust")
.itemInputs("2x gtceu:certus_quartz_frame")
.itemInputs("gtceu:cupronickel_coil_block")
.itemInputs("gtceu:lv_field_generator")
.itemOutputs("kubejs:fluixcoil")
.EUt(500)
.duration(200)

//OTWACAsing
event.recipes.gtceu.precisionassembler("OTWACasing")
.itemInputs("32x gtceu:silver_nickle_foil")
.itemInputs("6x gtceu:fluixsteel_plate")
.itemInputs("4x gtceu:mv_robot_arm")
.itemInputs("2x gtceu:fluixsteel_frame")
.itemInputs("gtceu:mv_sensor")
.itemOutputs("kubejs:owassemblycasing")
.inputFluids("gtceu:lubricant 288")
.inputFluids("gtceu:polyvinyl_chloride 288")
.EUt(500)
.duration(200)

//FluixDust
event.recipes.gtceu.mixer("FluixDust")
.itemInputs("8x gtceu:steel_dust")
.itemInputs("6x ae2:fluix_dust")
.itemInputs("2x gtceu:chromium_dust")
.itemOutputs("16x gtceu:fluixsteel_dust")
.EUt(120)
.duration(200)

//AlientechAssemblyline
event.recipes.gtceu.precisionassembler("AlientechAssemblyline")
.itemInputs("4x gtceu:hv_electric_pump")
.itemInputs("4x gtceu:double_desh_plate")
.itemInputs("4x #gtceu:circuits/iv")
.itemInputs("2x gtceu:desh_frame")
.itemInputs("2x ae2:mysterious_cube")
.itemInputs("2x kubejs:energy_manager1")
.itemInputs("gtceu:emassemblyline")
.itemOutputs("gtceu:alien_tech_assemblyline")
.inputFluids("gtceu:aluminium 1440")
.inputFluids("gtceu:lubricant 576")
.EUt(500)
.duration(1000)

//EnergyManager1 
event.recipes.gtceu.precisionassembler("EnergyManager1")
.itemInputs("16x gtceu:resistor")
.itemInputs("16x gtceu:capacitor")
.itemInputs("16x gtceu:fine_platinum_wire")
.itemInputs("2x gtceu:plastic_printed_circuit_board")
.itemInputs("#gtceu:circuits/hv")
.itemInputs("gtceu:lv_voltage_coil")
.itemOutputs("kubejs:energy_manager1")
.inputFluids("gtceu:soldering_alloy 144")
.inputFluids("gtceu:glue 144")
.EUt(120)
.duration(400)

//LunarWater
event.recipes.gtceu.fluid_heater("lunar_water")
.itemInputs("ad_astra:ice_shard")
.outputFluids("gtceu:lunar_water 144")
.EUt(30)
.duration(200)
//WaterPurification
event.recipes.gtceu.centrifuge("lunardust_dust")
.chancedOutput("gtceu:lunardust_dust" ,1000 ,1000)
.chancedOutput("gtceu:purifiedlunardust_dust" ,1000 ,1000)
.chancedOutput("gtceu:stone_dust" ,8000 ,1000)
.inputFluids("gtceu:lunar_water 288")
.outputFluids("gtceu:purified_lunar_water 144")
.EUt(120)
.duration(400)
//Waterdestilation
event.recipes.gtceu.distillation_tower("xenon")
.inputFluids("gtceu:purified_lunar_water 864")
.outputFluids("gtceu:xenon 144")
.outputFluids("gtceu:krypton 144")
.outputFluids("gtceu:hydrogen 144")
.outputFluids("gtceu:oxygen 288")
.outputFluids("gtceu:radon 144")
.duration(600)
.EUt(500)

//ExtendedMacerator
event.shaped("gtceu:extendedmacerator", [
    "ABA",
    "CDC",
    "ABA"
], {
    A: "gtceu:solid_machine_casing",
    B: "gtceu:steel_gear",
    C: "gtceu:micro_processor_computer",
    D: "gtceu:hv_macerator"
})

//Mixatron
event.recipes.gtceu.assembler("mixatron")
.itemInputs("4x gtceu:hv_mixer")
.itemInputs("3x #gtceu:circuits/ev")
.itemInputs("4x gtceu:hv_electric_motor")
.itemInputs("2x gtceu:chromium_rotor")
.itemInputs("2x gtceu:desh_frame")
.itemOutputs("gtceu:mixatron")
.duration(400)
.EUt(500)

//ExtruderMax
event.recipes.gtceu.assembler("extendedextruder")
.itemInputs("4x gtceu:hv_extruder")
.itemInputs("3x #gtceu:circuits/ev")
.itemInputs("4x gtceu:hv_electric_piston")
.itemInputs("2x gtceu:cupronickel_coil_block")
.itemInputs("2x gtceu:desh_frame")
.itemOutputs("gtceu:extendedextruder")
.duration(400)
.EUt(500)

//PrecisionAssembler
event.recipes.gtceu.assembler("precision_assembler")
.itemInputs("2x gtceu:hv_machine_hull")
.itemInputs("3x gtceu:hv_robot_arm")
.itemInputs("4x #gtceu:circuits/ev")
.itemInputs("2x #gtceu:circuits/hv")
.itemInputs("2x gtceu:hv_electric_pump")
.itemInputs("2x gtceu:blue_steel_frame")
.itemOutputs("gtceu:precision_assembler")
.inputFluids("gtceu:lubricant 567")
.duration(400)
.EUt(500)

//rocketFuel
event.recipes.gtceu.mixer("fuel")
.itemInputs("minecraft:red_dye")
.inputFluids("gtceu:rocket_fuel 10000")
.outputFluids("ad_astra:fuel 10000")
.duration(100)
.EUt(500)

//PhotoResist
//Glycol
event.recipes.gtceu.chemical_reactor("nickeltetracarbonyl_dust")
.itemInputs("thermal:nickel_dust")
.itemOutputs("gtceu:nickeltetracarbonyl_dust")
.inputFluids("gtceu:carbon_dioxide 4000")
.circuit(10)
.duration(200)
.EUt(30)

event.recipes.gtceu.chemical_reactor("propionic_acid")
.notConsumable("gtceu:nickeltetracarbonyl_dust")
.inputFluids("gtceu:ethane 200")
.inputFluids("gtceu:carbon_monoxide 200")
.inputFluids("minecraft:water 100")
.outputFluids("gtceu:propionic_acid 500")
.circuit(10)
.duration(400)
.EUt(30)

event.recipes.gtceu.chemical_reactor("perpropionic_acid")
.inputFluids("gtceu:propionic_acid 500")
.inputFluids("gtceu:hydrogen_peroxide 100")
.outputFluids("gtceu:perpropionic_acid 400")
.outputFluids("minecraft:water 200")
.circuit(10)
.duration(300)
.EUt(30)

event.recipes.gtceu.chemical_reactor("perpropionic_acid2")
.inputFluids("gtceu:perpropionic_acid 500")
.inputFluids("gtceu:propene 500")
.outputFluids("gtceu:perpropionic_acid 400")
.outputFluids("gtceu:propylenoxid 600")
.circuit(10)
.duration(200)
.EUt(120)

event.recipes.gtceu.large_chemical_reactor("propylene_glycol_methyl_ether_acetate")
.inputFluids("gtceu:propylenoxid 400")
.inputFluids("gtceu:methanol 200")
.inputFluids("gtceu:acetic_acid 200")
.outputFluids("gtceu:propylene_glycol_methyl_ether_acetate 800")
.circuit(10)
.duration(200)
.EUt(500)

event.recipes.gtceu.chemical_reactor("benzoic_acid_dust")
.notConsumable("gtceu:cobalt_dust")
.itemOutputs("3x gtceu:benzoic_acid_dust")
.inputFluids("gtceu:toluene 100")
.inputFluids("gtceu:oxygen 200")
.circuit(10)
.duration(200)
.EUt(30)

event.recipes.gtceu.chemical_reactor("phosphortrichlorid")
.itemInputs("gtceu:phosphorus_dust")
.inputFluids("gtceu:chlorine 3000")
.outputFluids("gtceu:phosphortrichlorid 4000")
.circuit(10)
.duration(100)
.EUt(30)

event.recipes.gtceu.chemical_reactor("benzoylchlorid")
.itemInputs("gtceu:benzoic_acid_dust")
.inputFluids("gtceu:phosphortrichlorid 500")
.outputFluids("gtceu:benzoylchlorid 600")
.circuit(10)
.duration(400)
.EUt(30)

event.recipes.gtceu.chemical_reactor("dibenzoylperoxid_dust")
.itemOutputs("5x gtceu:dibenzoylperoxid_dust")
.itemOutputs("2x gtceu:salt_dust")
.inputFluids("gtceu:benzoylchlorid 250")
.inputFluids("gtceu:hydrogen_peroxide 500")
.circuit(10)
.duration(400)
.EUt(30)

event.recipes.gtceu.large_chemical_reactor("polymethylmethacrylat")
.itemInputs("gtceu:dibenzoylperoxid_dust")
.inputFluids("gtceu:methyl_methacrylate 400")
.outputFluids("gtceu:polymethylmethacrylat 500")
.circuit(10)
.duration(200)
.EUt(500)

event.recipes.gtceu.large_chemical_reactor("methyl_propionate")
.inputFluids("gtceu:ethylene 500")
.inputFluids("gtceu:carbon_monoxide 250")
.inputFluids("gtceu:methanol 250")
.outputFluids("gtceu:methyl_propionate 1000")
.circuit(10)
.duration(400)
.EUt(120)

event.recipes.gtceu.chemical_reactor("methyl_methacrylate")
.inputFluids("gtceu:methyl_propionate 1000")
.inputFluids("gtceu:formaldehyde 1000")
.outputFluids("gtceu:methyl_methacrylate 1000")
.outputFluids("minecraft:water 1000")
.circuit(10)
.duration(200)
.EUt(30)

})